ADMIN_PANELS = [
    # === COMMON ADMIN PATHS ===
    'admin', 'administrator', 'adminpanel', 'admin-panel', 'admin_area',
    'admin_login', 'admin-login', 'admincp', 'admincp.php', 'admin.php',
    'admin/index', 'admin/login', 'admin/dashboard', 'admin/home',
    'admin/panel', 'admin/control', 'admin/manager', 'admin/admin',
    'administrator/index', 'administrator/login', 'administrator/dashboard',
    'administrator/admin', 'administrator/panel', 'administrator/control',
    'admin-console', 'admin_console', 'admin-dashboard', 'admin_dashboard',
    'admin-control', 'admin_control', 'admin-manager', 'admin_manager',
    'admin-panel', 'admin_panel', 'admin-portal', 'admin_portal',
    
    # === LOGIN PAGES ===
    'login', 'logon', 'signin', 'sign-in', 'auth', 'authenticate',
    'login.php', 'login.asp', 'login.aspx', 'login.jsp',
    'signin.php', 'signin.asp', 'signin.aspx', 'signin.jsp',
    'logon.php', 'logon.asp', 'logon.aspx', 'logon.jsp',
    'user/login', 'user/signin', 'user/auth', 'user/authenticate',
    'account/login', 'account/signin', 'account/auth',
    'panel/login', 'panel/signin', 'panel/auth',
    'admin/login.php', 'admin/signin.php', 'admin/auth.php',
    'administrator/login.php', 'administrator/signin.php',
    'auth/login', 'auth/signin', 'auth/admin',
    'login/admin', 'login/administrator', 'login/panel',
    'signin/admin', 'signin/administrator', 'signin/panel',
    'logon/admin', 'logon/administrator', 'logon/panel',
    
    # === DASHBOARD/CONTROL PANELS ===
    'dashboard', 'dashboard.php', 'dashboard.asp', 'dashboard.aspx',
    'control', 'control.php', 'control.asp', 'control.aspx',
    'panel', 'panel.php', 'panel.asp', 'panel.aspx',
    'cp', 'cpanel', 'webpanel', 'web-panel', 'controlpanel',
    'control-panel', 'dashboard/index', 'dashboard/home',
    'panel/index', 'panel/home', 'cp/index', 'cp/home',
    'admin/dashboard.php', 'admin/control.php', 'admin/panel.php',
    'dashboard/admin', 'dashboard/administrator', 'dashboard/panel',
    'control/admin', 'control/administrator', 'control/panel',
    'panel/admin', 'panel/administrator', 'panel/control',
    'cp/admin', 'cp/administrator', 'cp/panel',
    'cpanel/admin', 'cpanel/administrator', 'cpanel/panel',
    
    # === WORDPRESS ===
    'wp-admin', 'wp-login', 'wp-admin/admin.php', 'wp-admin/index.php',
    'wp-admin/dashboard', 'wp-admin/login', 'wp-admin/post.php',
    'wp-content', 'wp-includes', 'wp-config.php', 'wp-settings.php',
    'wp-admin/admin-ajax.php', 'wp-admin/admin-post.php',
    'wp-admin/async-upload.php', 'wp-admin/authorize-application.php',
    'wp-admin/comment.php', 'wp-admin/credits.php', 'wp-admin/customize.php',
    'wp-admin/edit-comments.php', 'wp-admin/edit-form-advanced.php',
    'wp-admin/edit-link-categories.php', 'wp-admin/edit-tag-form.php',
    'wp-admin/export.php', 'wp-admin/import.php', 'wp-admin/index.php',
    'wp-admin/link-add.php', 'wp-admin/link-manager.php', 'wp-admin/media-new.php',
    'wp-admin/network', 'wp-admin/options-general.php', 'wp-admin/options-media.php',
    'wp-admin/options-permalink.php', 'wp-admin/options-reading.php',
    'wp-admin/options-writing.php', 'wp-admin/plugin-editor.php',
    'wp-admin/plugin-install.php', 'wp-admin/plugins.php', 'wp-admin/post-new.php',
    'wp-admin/post.php', 'wp-admin/press-this.php', 'wp-admin/privacy.php',
    'wp-admin/profile.php', 'wp-admin/revision.php', 'wp-admin/setup-config.php',
    'wp-admin/site-health.php', 'wp-admin/theme-editor.php', 'wp-admin/theme-install.php',
    'wp-admin/themes.php', 'wp-admin/tools.php', 'wp-admin/update-core.php',
    'wp-admin/update.php', 'wp-admin/upload.php', 'wp-admin/user-edit.php',
    'wp-admin/user-new.php', 'wp-admin/users.php', 'wp-admin/widgets.php',
    'wp-admin/network/admin.php', 'wp-admin/network/dashboard.php',
    'wp-admin/network/sites.php', 'wp-admin/network/users.php',
    'wp-admin/network/themes.php', 'wp-admin/network/plugins.php',
    'wp-admin/network/settings.php', 'wp-admin/network/upgrade.php',
    'wp-login.php', 'wp-signup.php', 'wp-activate.php', 'wp-register.php',
    
    # === JOOMLA ===
    'administrator', 'administrator/index.php', 'administrator/login.php',
    'administrator/logout.php', 'administrator/control.php',
    'administrator/panel.php', 'administrator/dashboard.php',
    'administrator/components', 'administrator/modules', 'administrator/templates',
    'administrator/language', 'administrator/backups', 'administrator/cache',
    'administrator/help', 'administrator/images', 'administrator/includes',
    'administrator/logs', 'administrator/media', 'administrator/plugins',
    'administrator/manifests', 'administrator/configuration.php',
    'administrator/global-configuration', 'administrator/content',
    'administrator/menu', 'administrator/articles', 'administrator/categories',
    'administrator/media-manager', 'administrator/user-manager',
    'administrator/module-manager', 'administrator/plugin-manager',
    'administrator/template-manager', 'administrator/language-manager',
    'administrator/extension-manager', 'administrator/maintenance',
    'administrator/system-information', 'administrator/global-checkin',
    'administrator/clear-cache', 'administrator/purge-expired',
    
    # === DRUPAL ===
    'admin/dashboard', 'admin/content', 'admin/structure', 'admin/appearance',
    'admin/people', 'admin/modules', 'admin/config', 'admin/reports',
    'admin/help', 'admin/toolbar', 'admin/compact', 'admin/theme',
    'admin/config/people', 'admin/config/regional', 'admin/config/system',
    'admin/config/content', 'admin/config/media', 'admin/config/search',
    'admin/config/development', 'admin/config/services', 'admin/config/workflow',
    'admin/config/performance', 'admin/config/logging', 'admin/config/security',
    'admin/config/user-interface', 'admin/config/translation',
    'admin/config/administration', 'admin/config/web-services',
    'admin/structure/types', 'admin/structure/block', 'admin/structure/menu',
    'admin/structure/taxonomy', 'admin/structure/views', 'admin/structure/pages',
    'admin/structure/contact', 'admin/structure/file-system',
    'admin/appearance/settings', 'admin/appearance/install',
    'admin/people/permissions', 'admin/people/roles', 'admin/people/create',
    'admin/modules/install', 'admin/modules/uninstall', 'admin/modules/update',
    'admin/reports/status', 'admin/reports/updates', 'admin/reports/errors',
    'admin/reports/fields', 'admin/reports/search', 'admin/reports/hits',
    'admin/reports/dblog', 'admin/reports/access-denied',
    
    # === MAGENTO ===
    'admin', 'admin/index', 'admin/login', 'admin/dashboard',
    'admin/catalog', 'admin/sales', 'admin/customer', 'admin/report',
    'admin/system', 'admin/config', 'admin/backup', 'admin/import',
    'admin/export', 'admin/cache', 'admin/index/index',
    'admin/catalog/product', 'admin/catalog/category', 'admin/catalog/attribute',
    'admin/sales/order', 'admin/sales/invoice', 'admin/sales/shipment',
    'admin/sales/creditmemo', 'admin/customer/index', 'admin/customer/group',
    'admin/report/sales', 'admin/report/customer', 'admin/report/product',
    'admin/system/store', 'admin/system/website', 'admin/system/config',
    'admin/system/design', 'admin/system/importexport', 'admin/system/index',
    'admin/system/backup', 'admin/system/cache', 'admin/system/currency',
    'admin/system/tax', 'admin/system/email', 'admin/system/variables',
    'admin/system/translation', 'admin/system/encryption', 'admin/system/media',
    'admin/checkout', 'admin/payment', 'admin/shipping', 'admin/tax',
    'admin/review', 'admin/rating', 'admin/poll', 'admin/newsletter',
    
    # === PRESTASHOP ===
    'admin123', 'admin-dev', 'admin/index.php', 'admin/login.php',
    'admin/dashboard.php', 'admin/catalog.php', 'admin/orders.php',
    'admin/customers.php', 'admin/stats.php', 'admin/modules.php',
    'admin/configuration.php', 'admin/backup.php', 'admin/import.php',
    'admin/products', 'admin/categories', 'admin/attributes', 'admin/features',
    'admin/combinations', 'admin/suppliers', 'admin/manufacturers',
    'admin/customers', 'admin/addresses', 'admin/orders', 'admin/invoices',
    'admin/cart', 'admin/payments', 'admin/shipping', 'admin/taxes',
    'admin/modules', 'admin/themes', 'admin/translations', 'admin/employees',
    'admin/permissions', 'admin/profiles', 'admin/stores', 'admin/warehouses',
    'admin/stock', 'admin/supply-orders', 'admin/carriers', 'admin/zones',
    'admin/countries', 'admin/states', 'admin/currencies', 'admin/languages',
    'admin/meta-tags', 'admin/seo', 'admin/url-rewrites', 'admin/sitemap',
    'admin/performance', 'admin/maintenance', 'admin/logs', 'admin/statistics',
    
    # === OPENCART ===
    'admin', 'admin/index.php', 'admin/login.php', 'admin/dashboard.php',
    'admin/catalog.php', 'admin/sale.php', 'admin/customer.php',
    'admin/report.php', 'admin/system.php', 'admin/extension.php',
    'admin/module.php', 'admin/backup.php', 'admin/import.php',
    'admin/catalog/product', 'admin/catalog/category', 'admin/catalog/manufacturer',
    'admin/catalog/download', 'admin/catalog/review', 'admin/catalog/information',
    'admin/sale/order', 'admin/sale/recurring', 'admin/sale/return',
    'admin/customer/customer', 'admin/customer/group', 'admin/customer/custom-field',
    'admin/report/sale', 'admin/report/product', 'admin/report/customer',
    'admin/system/setting', 'admin/system/design', 'admin/system/user',
    'admin/system/api', 'admin/system/backup', 'admin/system/upgrade',
    'admin/extension/module', 'admin/extension/payment', 'admin/extension/shipping',
    'admin/extension/total', 'admin/extension/feed', 'admin/extension/report',
    'admin/extension/theme', 'admin/extension/analytics', 'admin/extension/captcha',
    'admin/extension/other', 'admin/design/layout', 'admin/design/banner',
    'admin/design/seo-url', 'admin/marketplace', 'admin/installer',
    
    # === PHP-BASED SYSTEMS ===
    'phpmyadmin', 'pma', 'mysql', 'myadmin', 'dbadmin', 'database',
    'phpmyadmin/index.php', 'phpmyadmin/login.php', 'pma/index.php',
    'mysql/index.php', 'mysql/login.php', 'dbadmin/index.php',
    'adminer', 'adminer.php', 'adminer/index.php', 'sqladmin',
    'mysqladmin', 'mysqldb', 'database-admin', 'db-management',
    'myphpadmin', 'phpadmin', 'phpmysql', 'mysql-admin', 'db-manager',
    'sql-manager', 'phpmyadmin4', 'pma4', 'mysql-manager', 'database-manager',
    'phpmyadmin3', 'pma3', 'mysql3', 'db3', 'phpmyadmin2', 'pma2',
    'mysql2', 'db2', 'myadmin', 'my-admin', 'db-admin', 'sql-admin',
    'php-myadmin', 'php-my-admin', 'mysql-admin', 'mysql-management',
    
    # === CUSTOM ADMIN PATHS ===
    'manage', 'manager', 'management', 'manage.php', 'manager.php',
    'management.php', 'manage/index', 'manager/index', 'management/index',
    'manage/login', 'manager/login', 'management/login',
    'manage/dashboard', 'manager/dashboard', 'management/dashboard',
    'site-admin', 'siteadmin', 'siteadmin/index', 'site-admin/index',
    'webadmin', 'web-admin', 'webadmin/index', 'web-admin/index',
    'sysadmin', 'system-admin', 'sysadmin/index', 'system-admin/index',
    'root', 'root/index', 'root/login', 'root/dashboard',
    'secure', 'secure/index', 'secure/login', 'secure/dashboard',
    'protected', 'protected/index', 'protected/login',
    'private', 'private/index', 'private/login',
    'restricted', 'restricted/index', 'restricted/login',
    'backend', 'backend/index', 'backend/login', 'backend/dashboard',
    'backoffice', 'backoffice/index', 'backoffice/login',
    'frontend', 'frontend/index', 'frontend/login',
    'internal', 'internal/index', 'internal/login',
    'intranet', 'intranet/index', 'intranet/login',
    'staff', 'staff/index', 'staff/login', 'staff/dashboard',
    'employee', 'employee/index', 'employee/login',
    'member', 'member/index', 'member/login', 'member/dashboard',
    'portal', 'portal/index', 'portal/login', 'portal/dashboard',
    'gateway', 'gateway/index', 'gateway/login',
    
    # === TECH-SPECIFIC ===
    'tomcat', 'tomcat-manager', 'manager/html', 'manager/status',
    'manager/jmxproxy', 'manager/roles', 'manager/sessions',
    'tomcat/index', 'tomcat/login', 'tomcat/dashboard',
    'catalina', 'catalina/index', 'catalina/login',
    'jboss', 'jboss-admin', 'jboss-management', 'jboss-console',
    'jboss/index', 'jboss/login', 'jboss/dashboard',
    'websphere', 'websphere-admin', 'websphere-management',
    'websphere/index', 'websphere/login', 'websphere/dashboard',
    'weblogic', 'weblogic-admin', 'weblogic-console',
    'weblogic/index', 'weblogic/login', 'weblogic/dashboard',
    'glassfish', 'glassfish-admin', 'glassfish-console',
    'glassfish/index', 'glassfish/login', 'glassfish/dashboard',
    'nginx', 'nginx-admin', 'nginx-status', 'nginx-rtmp',
    'nginx/index', 'nginx/login', 'nginx/dashboard',
    'apache', 'apache-admin', 'apache-status', 'apache-info',
    'apache/index', 'apache/login', 'apache/dashboard',
    'wildfly', 'wildfly-admin', 'wildfly-management',
    'wildfly/index', 'wildfly/login', 'wildfly/dashboard',
    'jetty', 'jetty-admin', 'jetty-management',
    'jetty/index', 'jetty/login', 'jetty/dashboard',
    
    # === DEVELOPMENT TOOLS ===
    'phpinfo', 'phpinfo.php', 'info.php', 'php.php',
    'phpMyAdmin', 'adminer.php', 'dbadmin.php',
    'test', 'test.php', 'test.html', 'test/index',
    'dev', 'dev.php', 'dev/index', 'development',
    'staging', 'stage', 'staging/index', 'stage/index',
    'sandbox', 'sandbox/index', 'sandbox/login',
    'demo', 'demo/index', 'demo/login', 'demo/dashboard',
    'beta', 'beta/index', 'beta/login', 'beta/dashboard',
    'alpha', 'alpha/index', 'alpha/login', 'alpha/dashboard',
    'prototype', 'prototype/index', 'prototype/login',
    'poc', 'poc/index', 'poc/login', 'poc/dashboard',
    'experimental', 'experimental/index', 'experimental/login',
    'testing', 'testing/index', 'testing/login', 'testing/dashboard',
    'debug', 'debug/index', 'debug/login', 'debug/dashboard',
    'troubleshoot', 'troubleshoot/index', 'troubleshoot/login',
    'diagnostic', 'diagnostic/index', 'diagnostic/login',
    'monitor', 'monitor/index', 'monitor/login', 'monitor/dashboard',
    'metrics', 'metrics/index', 'metrics/login', 'metrics/dashboard',
    'analytics', 'analytics/index', 'analytics/login', 'analytics/dashboard',
    
    # === BACKUPS AND TEMP FILES ===
    'backup', 'backups', 'backup.zip', 'backup.tar.gz',
    'dump', 'dumps', 'dump.sql', 'dump.zip',
    'temp', 'tmp', 'temp/index', 'tmp/index',
    'cache', 'cache/index', 'cached', 'cached/index',
    'archive', 'archives', 'archive.zip', 'archive.tar.gz',
    'old', 'old/index', 'old/login', 'old/dashboard',
    'copy', 'copy/index', 'copy/login', 'copy/dashboard',
    'bak', 'bak/index', 'bak/login', 'bak/dashboard',
    'snapshot', 'snapshot/index', 'snapshot/login',
    'restore', 'restore/index', 'restore/login',
    'recovery', 'recovery/index', 'recovery/login',
    
    # === CONFIGURATION FILES ===
    'config', 'config.php', 'config.json', 'config.yml',
    '.env', '.git', '.svn', '.htaccess', '.htpasswd',
    'robots.txt', 'sitemap.xml', 'crossdomain.xml',
    'web.config', 'app.config', 'database.config',
    'settings', 'settings.php', 'settings.json', 'settings.yml',
    'configuration', 'configuration.php', 'configuration.json',
    '.git/config', '.git/HEAD', '.git/index', '.git/logs',
    '.svn/entries', '.svn/wc.db', '.svn/format',
    'composer.json', 'composer.lock', 'package.json', 'package-lock.json',
    'yarn.lock', 'Gemfile', 'Gemfile.lock', 'Pipfile', 'Pipfile.lock',
    
    # === API ENDPOINTS ===
    'api', 'api/v1', 'api/v2', 'api/v3', 'api/index',
    'rest', 'rest/api', 'rest/index', 'rest/v1',
    'graphql', 'graphiql', 'graphql/explorer',
    'swagger', 'swagger-ui', 'api-docs', 'docs',
    'api/admin', 'api/admin/index', 'api/admin/login',
    'api/dashboard', 'api/dashboard/index', 'api/dashboard/login',
    'rest/admin', 'rest/admin/index', 'rest/admin/login',
    'graphql/admin', 'graphql/admin/index', 'graphql/admin/login',
    'api/v1/admin', 'api/v2/admin', 'api/v3/admin',
    'rest/v1/admin', 'rest/v2/admin', 'rest/v3/admin',
    'api-gateway', 'api-gateway/admin', 'api-gateway/dashboard',
    'apigateway', 'apigateway/admin', 'apigateway/dashboard',
    
    # === USER MANAGEMENT ===
    'users', 'user', 'user/index', 'users/index',
    'accounts', 'account', 'accounts/index', 'account/index',
    'profile', 'profiles', 'profile/index', 'profiles/index',
    'register', 'registration', 'register/index', 'registration/index',
    'signup', 'signup.php', 'signup/index', 'signup/login',
    'user-admin', 'user-admin/index', 'user-admin/login',
    'users-admin', 'users-admin/index', 'users-admin/login',
    'account-admin', 'account-admin/index', 'account-admin/login',
    'accounts-admin', 'accounts-admin/index', 'accounts-admin/login',
    'profile-admin', 'profile-admin/index', 'profile-admin/login',
    'profiles-admin', 'profiles-admin/index', 'profiles-admin/login',
    'user-management', 'user-management/index', 'user-management/login',
    'users-management', 'users-management/index', 'users-management/login',
    'account-management', 'account-management/index', 'account-management/login',
    'accounts-management', 'accounts-management/index', 'accounts-management/login',
    
    # === SHOPPING/E-COMMERCE ===
    'cart', 'cart/index', 'cart/view', 'cart/checkout',
    'checkout', 'checkout/index', 'checkout/payment',
    'orders', 'orders/index', 'orders/view', 'orders/history',
    'products', 'products/index', 'products/view', 'products/search',
    'shop', 'shop/index', 'shop/cart', 'shop/checkout',
    'store', 'store/index', 'store/cart', 'store/checkout',
    'marketplace', 'marketplace/index', 'marketplace/cart',
    'ecommerce', 'ecommerce/index', 'ecommerce/cart',
    'payment', 'payment/index', 'payment/checkout',
    'payments', 'payments/index', 'payments/checkout',
    'billing', 'billing/index', 'billing/cart', 'billing/checkout',
    'invoice', 'invoice/index', 'invoice/cart', 'invoice/checkout',
    'invoices', 'invoices/index', 'invoices/cart', 'invoices/checkout',
    'cart-admin', 'cart-admin/index', 'cart-admin/login',
    'checkout-admin', 'checkout-admin/index', 'checkout-admin/login',
    'orders-admin', 'orders-admin/index', 'orders-admin/login',
    'products-admin', 'products-admin/index', 'products-admin/login',
    'shop-admin', 'shop-admin/index', 'shop-admin/login',
    'store-admin', 'store-admin/index', 'store-admin/login',
    'ecommerce-admin', 'ecommerce-admin/index', 'ecommerce-admin/login',
    
    # === SOCIAL FEATURES ===
    'forum', 'forum/index', 'forum/login', 'forum/register',
    'board', 'board/index', 'board/login', 'board/register',
    'community', 'community/index', 'community/login',
    'blog', 'blog/index', 'blog/admin', 'blog/dashboard',
    'news', 'news/index', 'news/admin', 'news/dashboard',
    'forum-admin', 'forum-admin/index', 'forum-admin/login',
    'board-admin', 'board-admin/index', 'board-admin/login',
    'community-admin', 'community-admin/index', 'community-admin/login',
    'blog-admin', 'blog-admin/index', 'blog-admin/login',
    'news-admin', 'news-admin/index', 'news-admin/login',
    'discussion', 'discussion/index', 'discussion/login',
    'discussion-admin', 'discussion-admin/index', 'discussion-admin/login',
    'chat', 'chat/index', 'chat/login', 'chat/admin',
    'chat-admin', 'chat-admin/index', 'chat-admin/login',
    'messaging', 'messaging/index', 'messaging/login',
    'messaging-admin', 'messaging-admin/index', 'messaging-admin/login',
    
    # === MEDIA FILES ===
    'images', 'images/index', 'images/uploads', 'uploads',
    'files', 'files/index', 'files/uploads', 'download',
    'media', 'media/index', 'media/uploads', 'gallery',
    'assets', 'assets/index', 'assets/images', 'assets/css',
    'images-admin', 'images-admin/index', 'images-admin/login',
    'files-admin', 'files-admin/index', 'files-admin/login',
    'media-admin', 'media-admin/index', 'media-admin/login',
    'gallery-admin', 'gallery-admin/index', 'gallery-admin/login',
    'uploads-admin', 'uploads-admin/index', 'uploads-admin/login',
    'download-admin', 'download-admin/index', 'download-admin/login',
    'assets-admin', 'assets-admin/index', 'assets-admin/login',
    'image-manager', 'image-manager/index', 'image-manager/login',
    'file-manager', 'file-manager/index', 'file-manager/login',
    'media-manager', 'media-manager/index', 'media-manager/login',
    'asset-manager', 'asset-manager/index', 'asset-manager/login',
    
    # === SECURITY-RELATED ===
    'security', 'secure', 'safe', 'protected', 'private',
    'encrypt', 'encryption', 'crypt', 'crypto',
    'ssl', 'tls', 'https', 'secure/index', 'secure/login',
    'security-admin', 'security-admin/index', 'security-admin/login',
    'secure-admin', 'secure-admin/index', 'secure-admin/login',
    'firewall', 'firewall/index', 'firewall/login', 'firewall/admin',
    'waf', 'waf/index', 'waf/login', 'waf/admin',
    'ids', 'ids/index', 'ids/login', 'ids/admin',
    'ips', 'ips/index', 'ips/login', 'ips/admin',
    'antivirus', 'antivirus/index', 'antivirus/login',
    'malware', 'malware/index', 'malware/login',
    'scanner', 'scanner/index', 'scanner/login',
    'vulnerability', 'vulnerability/index', 'vulnerability/login',
    'pentest', 'pentest/index', 'pentest/login',
    'exploit', 'exploit/index', 'exploit/login',
    
    # === MONITORING ===
    'stats', 'statistics', 'stats/index', 'statistics/index',
    'status', 'status/index', 'server-status', 'server-info',
    'monitor', 'monitoring', 'monitor/index', 'monitoring/index',
    'health', 'healthcheck', 'health/index', 'health/check',
    'performance', 'performance/index', 'performance/login',
    'performance-admin', 'performance-admin/index', 'performance-admin/login',
    'uptime', 'uptime/index', 'uptime/login', 'uptime/admin',
    'ping', 'ping/index', 'ping/login', 'ping/admin',
    'probe', 'probe/index', 'probe/login', 'probe/admin',
    'watchdog', 'watchdog/index', 'watchdog/login',
    'watchdog-admin', 'watchdog-admin/index', 'watchdog-admin/login',
    
    # === LOGS ===
    'logs', 'log', 'logs/index', 'log/index',
    'logviewer', 'log-viewer', 'logs/view', 'log/view',
    'error', 'errors', 'error/index', 'errors/index',
    'audit', 'audit/index', 'audit/login', 'audit/admin',
    'audit-logs', 'audit-logs/index', 'audit-logs/login',
    'logging', 'logging/index', 'logging/login',
    'logging-admin', 'logging-admin/index', 'logging-admin/login',
    'trace', 'trace/index', 'trace/login', 'trace/admin',
    'debug-logs', 'debug-logs/index', 'debug-logs/login',
    'access-logs', 'access-logs/index', 'access-logs/login',
    'system-logs', 'system-logs/index', 'system-logs/login',
    'app-logs', 'app-logs/index', 'app-logs/login',
    
    # === CLOUD AND HOSTING ADMIN ===
    'cpanel', 'whm', 'webmail', 'webdisk',
    'cpanel/index', 'cpanel/login', 'cpanel/dashboard',
    'whm/index', 'whm/login', 'whm/dashboard',
    'webmail/index', 'webmail/login', 'webmail/dashboard',
    'plesk', 'plesk/index', 'plesk/login', 'plesk/dashboard',
    'directadmin', 'directadmin/index', 'directadmin/login',
    'ispconfig', 'ispconfig/index', 'ispconfig/login',
    'vestacp', 'vestacp/index', 'vestacp/login',
    'virtualmin', 'virtualmin/index', 'virtualmin/login',
    'webmin', 'webmin/index', 'webmin/login',
    'cloud', 'cloud/index', 'cloud/login', 'cloud/dashboard',
    'cloud-admin', 'cloud-admin/index', 'cloud-admin/login',
    'hosting', 'hosting/index', 'hosting/login',
    'hosting-admin', 'hosting-admin/index', 'hosting-admin/login',
    'server', 'server/index', 'server/login', 'server/dashboard',
    'server-admin', 'server-admin/index', 'server-admin/login',
    'vps', 'vps/index', 'vps/login', 'vps/dashboard',
    'vps-admin', 'vps-admin/index', 'vps-admin/login',
    'dedicated', 'dedicated/index', 'dedicated/login',
    'dedicated-admin', 'dedicated-admin/index', 'dedicated-admin/login',
    
    # === DOCKER AND CONTAINER ADMIN ===
    'docker', 'docker-admin', 'docker/dashboard',
    'kubernetes', 'k8s', 'kubernetes-dashboard',
    'rancher', 'rancher/index', 'rancher/dashboard',
    'portainer', 'portainer/index', 'portainer/dashboard',
    'docker-registry', 'docker-registry/index', 'docker-registry/login',
    'kubectl', 'kubectl/index', 'kubectl/login',
    'helm', 'helm/index', 'helm/login', 'helm/dashboard',
    'container', 'container/index', 'container/login',
    'container-admin', 'container-admin/index', 'container-admin/login',
    'orchestration', 'orchestration/index', 'orchestration/login',
    'kube', 'kube/index', 'kube/login', 'kube/dashboard',
    'k8s-dashboard', 'k8s-dashboard/index', 'k8s-dashboard/login',
    
    # === DATABASE ADMIN ===
    'phpmyadmin', 'pma', 'mysql', 'dbadmin', 'database',
    'adminer', 'adminer.php', 'sqladmin', 'mysqladmin',
    'phpmyadmin/index', 'pma/index', 'mysql/index',
    'phpmyadmin/login', 'pma/login', 'mysql/login',
    'postgres', 'postgresql', 'pgadmin', 'pgsql',
    'postgres/index', 'postgres/login', 'postgres/dashboard',
    'pgadmin/index', 'pgadmin/login', 'pgadmin/dashboard',
    'mongodb', 'mongo', 'mongodb/index', 'mongo/index',
    'mongodb/login', 'mongo/login', 'mongodb/dashboard',
    'redis', 'redis/index', 'redis/login', 'redis/dashboard',
    'elasticsearch', 'elastic', 'elasticsearch/index',
    'elasticsearch/login', 'elasticsearch/dashboard',
    'cassandra', 'cassandra/index', 'cassandra/login',
    'couchdb', 'couchdb/index', 'couchdb/login',
    'neo4j', 'neo4j/index', 'neo4j/login',
    'dynamodb', 'dynamodb/index', 'dynamodb/login',
    'sqlserver', 'sqlserver/index', 'sqlserver/login',
    'oracle', 'oracle/index', 'oracle/login',
    
    # === ADDITIONAL ADMIN PATHS ===
    'access', 'account-admin', 'account-management', 'accounts',
    'action', 'actions', 'activate', 'activation',
    'active', 'activity', 'add', 'admin-console',
    'admin-control', 'admin-home', 'admin-menu', 'admin-panel',
    'admin-tools', 'administration', 'administrative',
    'admins', 'affiliate', 'affiliates', 'ajax', 'analytics',
    'app', 'application', 'apps', 'assets', 'auth0', 'authorize',
    'authentication', 'authorization', 'auto', 'back', 'b2b',
    'b2c', 'backend', 'billing', 'branding', 'browse', 'bug',
    'bug-report', 'builder', 'business', 'cabinet', 'campaign',
    'campaigns', 'careers', 'catalog', 'category', 'changelog',
    'check', 'checkout', 'client', 'clients', 'cloud', 'code',
    'collaboration', 'commerce', 'community', 'company',
    'content', 'content-management', 'content-admin', 'context',
    'contracts', 'core', 'corporate', 'create', 'creative',
    'creator', 'credits', 'cron', 'cronjobs', 'custom',
    'customize', 'customer', 'dashboard-admin', 'data',
    'database-admin', 'debug', 'deploy', 'deployment', 'design',
    'developer', 'development', 'devtools', 'docs', 'documents',
    'domain', 'domains', 'downloads', 'draft', 'drafts',
    'dynamic', 'ecommerce', 'edit', 'editor', 'education',
    'email', 'email-admin', 'employee', 'employees', 'enterprise',
    'environment', 'error', 'errors', 'events', 'exchange',
    'executive', 'export', 'extension', 'extensions', 'external',
    'feature', 'features', 'feedback', 'file', 'file-manager',
    'files', 'finance', 'financial', 'form', 'forms', 'frontend',
    'gdpr', 'global', 'governance', 'graphql', 'group', 'groups',
    'guest', 'help', 'helpdesk', 'history', 'home', 'hosting',
    'hr', 'html', 'http', 'https', 'hub', 'identity', 'images',
    'index', 'info', 'information', 'infrastructure', 'insights',
    'integration', 'interactive', 'internal', 'inventory', 'investors',
    'invoice', 'invoices', 'job', 'jobs', 'json', 'knowledge',
    'knowledge-base', 'label', 'labels', 'language', 'layout',
    'leadership', 'learning', 'legal', 'library', 'licenses',
    'link', 'links', 'list', 'lists', 'live', 'local', 'locale',
    'location', 'lock', 'login', 'logout', 'logs', 'maintenance',
    'management', 'manager', 'marketing', 'marketplace', 'media',
    'member', 'members', 'membership', 'menu', 'message', 'messages',
    'meta', 'metrics', 'mining', 'mobile', 'model', 'models',
    'moderation', 'monitor', 'monitoring', 'multi', 'multimedia',
    'navigation', 'network', 'newsletter', 'node', 'notification',
    'notifications', 'oauth', 'office', 'online', 'operations',
    'opportunity', 'optimization', 'order', 'orders', 'org',
    'organization', 'page', 'pages', 'partner', 'partners',
    'password', 'passwords', 'payment', 'payments', 'performance',
    'permission', 'permissions', 'personal', 'phone', 'pipeline',
    'plan', 'plans', 'platform', 'plugin', 'plugins', 'policy',
    'portal', 'post', 'posts', 'power', 'preferences', 'premium',
    'press', 'preview', 'pricing', 'privacy', 'private', 'privilege',
    'process', 'product', 'production', 'products', 'profile',
    'program', 'progress', 'project', 'projects', 'promo', 'promotion',
    'proposals', 'protected', 'protocol', 'provider', 'public',
    'publish', 'publisher', 'purchases', 'query', 'queue', 'quick',
    'reports', 'repository', 'request', 'requests', 'research',
    'reset', 'resources', 'response', 'resume', 'revenue', 'review',
    'reviews', 'roadmap', 'role', 'roles', 'root', 'safety',
    'sales', 'sample', 'sandbox', 'schedule', 'scheduler', 'schema',
    'search', 'secure', 'security', 'segment', 'server', 'service',
    'services', 'session', 'sessions', 'settings', 'setup', 'sitemap',
    'software', 'solution', 'source', 'staff', 'stage', 'staging',
    'standard', 'start', 'static', 'statistics', 'status', 'storage',
    'store', 'strategy', 'structure', 'studio', 'style', 'styles',
    'subscription', 'subscribers', 'support', 'survey', 'swagger',
    'sync', 'system', 'table', 'tables', 'tag', 'tags', 'task',
    'tasks', 'team', 'teams', 'technical', 'technology', 'template',
    'templates', 'test', 'testing', 'theme', 'themes', 'ticket',
    'tickets', 'time', 'timeline', 'tools', 'top', 'tokens',
    'track', 'tracking', 'traffic', 'training', 'transaction',
    'transactions', 'translate', 'translation', 'trash', 'travel',
    'tutorial', 'ui', 'unsubscribe', 'update', 'updates', 'upgrade',
    'upload', 'uploads', 'url', 'usage', 'user', 'utility',
    'validation', 'variable', 'vendor', 'verification', 'version',
    'video', 'videos', 'view', 'views', 'virtual', 'visibility',
    'vision', 'visual', 'vocabulary', 'waiting', 'web', 'webhook',
    'widget', 'widgets', 'wireframe', 'work', 'workflow', 'workspace',
    'xml', 'zone', 'admin-area', 'admin-portal', 'admin-console',
    'admin-tools', 'admin-interface', 'admin-dashboard', 'admin-system',
    'admin-modules', 'admin-users', 'admin-content', 'admin-media',
    'admin-reports', 'admin-settings', 'admin-backup', 'admin-restore',
    'admin-import', 'admin-export', 'admin-cache', 'admin-login',
    'admin-logout', 'admin-profile', 'admin-security', 'admin-log',
    'admin-error', 'admin-debug', 'admin-test', 'admin-demo',
    'admin-version', 'admin-update', 'admin-install', 'admin-migrate',
    
    # === NUMBERS AND VARIATIONS ===
    'admin1', 'admin2', 'admin3', 'admin4', 'admin5',
    'admin123', 'admin1234', 'admin12345',
    'administrator1', 'administrator2', 'administrator3',
    'admin001', 'admin002', 'admin003',
    'admin_1', 'admin_2', 'admin_3', 'admin_123',
    'admin-1', 'admin-2', 'admin-3', 'admin-123',
    'admin01', 'admin02', 'admin03', 'admin04', 'admin05',
    'admin10', 'admin20', 'admin30', 'admin40', 'admin50',
    'admin99', 'admin100', 'admin999',
    'administrator01', 'administrator02', 'administrator03',
    'administrator10', 'administrator20', 'administrator30',
    
    # === CASE VARIATIONS ===
    'Admin', 'Administrator', 'Login', 'Panel', 'Dashboard',
    'Control', 'Manage', 'Manager', 'Auth', 'Signin',
    'ADMIN', 'ADMINISTRATOR', 'LOGIN', 'PANEL', 'DASHBOARD',
    'CONTROL', 'MANAGE', 'MANAGER', 'AUTH', 'SIGNIN',
    'AdminPanel', 'LoginPanel', 'DashboardPanel',
    'AdminLogin', 'AdminAuth', 'AdminSignin',
    'AdminDashboard', 'AdminControl', 'AdminManage',
    'AdministratorPanel', 'AdministratorLogin',
    'AdministratorDashboard', 'AdministratorControl',
    'WebAdmin', 'WebAdministrator', 'WebLogin',
    'SiteAdmin', 'SiteAdministrator', 'SiteLogin',
    'SystemAdmin', 'SystemAdministrator', 'SystemLogin',
]

def get_admin_panels():
    return ADMIN_PANELS

def get_panel_count():
    return len(ADMIN_PANELS)
