SUBDOMAINS = [
    # Common subdomains
    'www', 'mail', 'ftp', 'localhost', 'webmail', 'smtp', 'pop', 'ns1', 
    'webdisk', 'ns2', 'cpanel', 'whm', 'autodiscover', 'autoconfig', 'm', 
    'imap', 'test', 'ns', 'blog', 'pop3', 'dev', 'www2', 'admin', 'forum', 
    'news', 'vpn', 'ns3', 'mail2', 'new', 'mysql', 'old', 'lists', 'support',
    'mobile', 'mx', 'static', 'docs', 'beta', 'shop', 'sql', 'secure', 
    'demo', 'cp', 'calendar', 'wiki', 'web', 'media', 'email', 'images',
    'img', 'video', 'download', 'dns', 'api', 'app', 'apps', 'store',
    'cart', 'checkout', 'payment', 'gateway', 'merchant', 'billing',
    'invoice', 'account', 'user', 'users', 'member', 'members', 'profile',
    'dashboard', 'panel', 'administrator', 'manage', 'manager', 'control',
    'system', 'server', 'host', 'hosting', 'cloud', 'backup', 'backups',
    'archive', 'data', 'database', 'cache', 'cdn', 'static', 'assets',
    'resources', 'downloads', 'uploads', 'files', 'audio', 'stream',
    'live', 'chat', 'talk', 'voice', 'sms', 'mms', 'push', 'notification',
    'alerts', 'monitor', 'metrics', 'analytics', 'stats', 'reports', 'logs',
    'debug', 'staging', 'stage', 'development', 'qa', 'uat', 'sandbox',
    'local', 'internal', 'private', 'secret', 'hidden', 'vault', 'secure',
    'auth', 'login', 'signin', 'oauth', 'openid', 'sso', 'identity',
    'token', 'passport', 'session', 'cookie', 'track', 'trace', 'audit',
    'compliance', 'gdpr', 'privacy', 'policy', 'terms', 'legal', 'help',
    'ticket', 'faq', 'knowledge', 'documentation', 'manual', 'guide',
    'tutorial', 'learn', 'training', 'education', 'course', 'academy',
    'university', 'school', 'college', 'campus', 'library', 'research',
    'lab', 'innovation', 'startup', 'venture', 'investor', 'partner',
    'affiliate', 'reseller', 'distributor', 'supplier', 'vendor', 'consultant',
    'agency', 'studio', 'creative', 'design', 'art', 'gallery', 'portfolio',
    'showcase', 'exhibition', 'event', 'conference', 'summit', 'meetup',
    'workshop', 'webinar', 'seminar', 'bootcamp', 'hackathon', 'competition',
    'challenge', 'prize', 'award', 'recognition', 'achievement', 'success',
    'story', 'testimonial', 'review', 'rating', 'feedback', 'survey', 'poll',
    'vote', 'election', 'ballot', 'referendum', 'petition', 'campaign',
    'cause', 'charity', 'donate', 'fundraiser', 'crowd', 'community',
    'discussion', 'board', 'thread', 'post', 'reply', 'comment', 'like',
    'share', 'follow', 'subscribe', 'unsubscribe', 'newsletter', 'digest',
    'daily', 'weekly', 'monthly', 'annual', 'report', 'summary', 'overview',
    'insight', 'trend', 'pattern', 'anomaly', 'alert', 'warning', 'critical',
    'emergency', 'disaster', 'recovery', 'business', 'enterprise', 'corporate',
    'company', 'organization', 'institution', 'department', 'division', 'unit',
    'team', 'squad', 'crew', 'staff', 'employee', 'contractor', 'freelancer',
    'advisor', 'mentor', 'coach', 'trainer',
    
    # Tech-related
    'git', 'github', 'gitlab', 'bitbucket', 'jenkins', 'jira', 'confluence',
    'sonarqube', 'nexus', 'artifactory', 'docker', 'k8s', 'kubernetes',
    'rancher', 'portainer', 'grafana', 'prometheus', 'elasticsearch', 'kibana',
    'logstash', 'splunk', 'datadog', 'newrelic', 'appdynamics', 'dynatrace',
    'zabbix', 'nagios', 'icinga', 'pagerduty', 'opsgenie', 'victorops',
    
    # Development
    'dev', 'dev1', 'dev2', 'dev3', 'dev4', 'dev5', 'test', 'test1', 'test2',
    'test3', 'stage', 'staging', 'staging1', 'staging2', 'preprod', 'pre-prod',
    'uat', 'uat1', 'uat2', 'qa', 'qa1', 'qa2', 'sandbox', 'sandbox1',
    'demo', 'demo1', 'demo2', 'prototype', 'poc', 'proof-of-concept',
    
    # Cloud providers
    'aws', 'azure', 'gcp', 'cloud', 'cloud1', 'cloud2', 'ec2', 's3', 'rds',
    'dynamodb', 'lambda', 'api-gateway', 'cloudfront', 'route53', 'elb',
    'alb', 'vpc', 'subnet', 'security-group', 'iam', 'kms', 'secrets-manager',
    
    # Microservices
    'auth', 'authentication', 'authorization', 'users', 'user-service',
    'accounts', 'account-service', 'profile', 'profile-service', 'payment',
    'payment-service', 'orders', 'order-service', 'products', 'product-service',
    'inventory', 'inventory-service', 'shipping', 'shipping-service',
    'notification', 'notification-service', 'email-service', 'sms-service',
    'push-service', 'analytics-service', 'reporting-service', 'logging-service',
    'monitoring-service', 'config-service', 'registry-service', 'gateway-service',
    
    # Databases
    'db', 'database', 'db1', 'db2', 'db3', 'mysql', 'postgres', 'mongo',
    'mongodb', 'redis', 'elastic', 'cassandra', 'couchdb', 'neo4j', 'dynamo',
    'sqlserver', 'oracle', 'db-admin', 'db-backup', 'db-replica', 'db-slave',
    
    # Mail servers
    'mail', 'mail1', 'mail2', 'mail3', 'email', 'smtp', 'pop', 'imap',
    'exchange', 'outlook', 'zimbra', 'roundcube', 'squirrelmail', 'rainloop',
    'mailman', 'lists', 'newsletter', 'bulk', 'spam', 'filter',
    
    # Game servers
    'game', 'games', 'gaming', 'play', 'server', 'lobby', 'matchmaking',
    'stats', 'leaderboard', 'rank', 'score', 'profile', 'inventory',
    'shop', 'store', 'marketplace', 'trade', 'auction', 'battle',
    
    # Streaming
    'stream', 'live', 'video', 'audio', 'media', 'cdn', 'edge', 'delivery',
    'playback', 'transcoding', 'encoder', 'decoder', 'hls', 'dash', 'rtmp',
    'webrtc', 'sip', 'voip', 'voice', 'call', 'conference',
    
    # IoT
    'iot', 'device', 'devices', 'sensor', 'sensors', 'gateway', 'hub',
    'controller', 'actuator', 'monitor', 'thermostat', 'camera', 'doorbell',
    'lock', 'alarm', 'security', 'automation', 'home', 'office', 'factory',
    
    # Social media
    'social', 'facebook', 'twitter', 'instagram', 'linkedin', 'youtube',
    'tiktok', 'snapchat', 'reddit', 'pinterest', 'tumblr', 'discord',
    'slack', 'teams', 'zoom', 'meet', 'webex', 'gotomeeting',
    
    # Additional common subdomains
    'abuse', 'ac', 'academia', 'academy', 'access', 'accounting', 'accounts',
    'action', 'active', 'ad', 'add', 'address', 'admin-console', 'admin-panel',
    'administration', 'ads', 'adv', 'advertising', 'af', 'affiliate', 'ag',
    'agency', 'aggregator', 'agile', 'agreement', 'ai', 'air', 'alerts',
    'alexa', 'algolia', 'alias', 'alpha', 'analytics', 'android', 'angular',
    'anime', 'announce', 'announcements', 'annual', 'answers', 'antivirus',
    'any', 'api-gateway', 'api-platform', 'api-rest', 'apollo', 'apple',
    'application', 'applications', 'approval', 'apps', 'archive', 'area',
    'artist', 'arts', 'ask', 'asp', 'aspnet', 'assets', 'assistant', 'at',
    'atlantis', 'atom', 'audio', 'audit', 'authenticate', 'author', 'authorize',
    'automation', 'autopilot', 'availability', 'aws', 'azure', 'b2b', 'b2c',
    'backup', 'backups', 'banner', 'base', 'batch', 'bay', 'beacon', 'beta',
    'billing', 'bin', 'biometrics', 'bitbucket', 'blackberry', 'blog', 'board',
    'bots', 'brand', 'branding', 'broadcast', 'broker', 'browser', 'btoa',
    'budget', 'build', 'builder', 'bulk', 'business', 'buzz', 'cache',
    'calendar', 'campaign', 'campaigns', 'campus', 'candidate', 'candidates',
    'canvas', 'care', 'career', 'careers', 'cart', 'catalog', 'catch', 'cc',
    'cdn', 'celery', 'center', 'central', 'certificate', 'certificates',
    'challenge', 'changes', 'channel', 'channels', 'charity', 'chart', 'charts',
    'chat', 'check', 'checkout', 'ci', 'circle', 'cities', 'city', 'cl',
    'class', 'classic', 'classroom', 'clear', 'client', 'clients', 'climate',
    'cloud', 'cloudfront', 'cm', 'cms', 'code', 'coder', 'codes', 'collab',
    'collaboration', 'collect', 'collector', 'college', 'com', 'comics',
    'commerce', 'commercial', 'commit', 'commitments', 'committee', 'common',
    'community', 'company', 'compare', 'compass', 'compliance', 'compute',
    'computer', 'con', 'concept', 'concern', 'condition', 'conf', 'conference',
    'config', 'configuration', 'confirm', 'connect', 'connection', 'connections',
    'console', 'consul', 'consult', 'consulting', 'consumer', 'contact',
    'container', 'contribute', 'control', 'controller', 'conversion', 'copy',
    'core', 'cors', 'cost', 'count', 'counter', 'countries', 'country',
    'coupon', 'coupons', 'course', 'courses', 'cpanel', 'crawl', 'create',
    'creative', 'creator', 'credit', 'credits', 'crm', 'crowd', 'crypto',
    'css', 'culture', 'currency', 'current', 'customer', 'customers',
    'customize', 'cyber', 'daemon', 'daily', 'dam', 'dance', 'dark', 'data',
    'database', 'databases', 'datacenter', 'datadog', 'datasets', 'date',
    'days', 'dba', 'dbadmin', 'de', 'dealer', 'debug', 'dec', 'decentral',
    'deck', 'declare', 'default', 'defender', 'define', 'del', 'delivery',
    'delta', 'demo', 'deploy', 'deployment', 'design', 'desk', 'desktop',
    'detect', 'detector', 'dev', 'developer', 'developers', 'development',
    'devices', 'devops', 'devtools', 'diagram', 'diet', 'digital', 'direct',
    'directory', 'disco', 'discord', 'discount', 'discounts', 'discover',
    'discovery', 'dispatch', 'display', 'dist', 'distribute', 'distributor',
    'diversity', 'diy', 'dm', 'dns', 'docs', 'document', 'documentation',
    'documents', 'domain', 'domains', 'donate', 'door', 'draft', 'dragon',
    'drupal', 'ds', 'dt', 'dub', 'dump', 'duo', 'dvd', 'dynamics', 'eagle',
    'earth', 'ease', 'east', 'easy', 'eat', 'eco', 'ecommerce', 'economy',
    'edge', 'edit', 'editor', 'edu', 'education', 'effect', 'elastic',
    'elasticsearch', 'elb', 'election', 'electric', 'elements', 'email',
    'emergency', 'emission', 'emp', 'employee', 'employees', 'employment',
    'empty', 'en', 'enable', 'encode', 'encrypt', 'end', 'endpoint', 'energy',
    'engage', 'engine', 'engineer', 'engineering', 'enhance', 'enterprise',
    'entertainment', 'environment', 'ep', 'epic', 'eq', 'equal', 'equip',
    'equipment', 'equity', 'error', 'es', 'escalation', 'escape', 'esp',
    'essay', 'estate', 'etc', 'ethics', 'europe', 'eval', 'event', 'events',
    'evidence', 'ex', 'exam', 'example', 'exchange', 'exclude', 'exec',
    'executive', 'exempt', 'exercise', 'exhibit', 'exhibition', 'exist',
    'exit', 'expand', 'expense', 'experiment', 'expert', 'experts', 'explore',
    'explorer', 'export', 'express', 'ext', 'extend', 'extension', 'extract',
    'ez', 'face', 'facebook', 'facet', 'facilitate', 'facility', 'fact',
    'factor', 'factory', 'faculty', 'fail', 'fair', 'fake', 'family', 'faq',
    'faqs', 'farm', 'farming', 'fast', 'fat', 'fault', 'fax', 'fc', 'fda',
    'fdic', 'fe', 'feature', 'features', 'feb', 'fed', 'federal', 'feed',
    'feedback', 'feeds', 'female', 'fest', 'festival', 'few', 'fff', 'field',
    'fields', 'file', 'files', 'film', 'finance', 'financial', 'find',
    'finder', 'fine', 'finger', 'fire', 'firebase', 'firewall', 'firm',
    'first', 'fitness', 'fix', 'fixture', 'flag', 'flash', 'flat', 'flex',
    'flight', 'flip', 'float', 'flood', 'floor', 'flow', 'flower', 'fluid',
    'fly', 'focus', 'folder', 'follow', 'footer', 'for', 'forbes', 'force',
    'forecast', 'foreign', 'forest', 'forge', 'forget', 'fork', 'form',
    'formal', 'format', 'forms', 'fort', 'forum', 'forward', 'foto', 'found',
    'foundation', 'founder', 'four', 'frame', 'framework', 'france', 'free',
    'freedom', 'freeze', 'french', 'frequency', 'fresh', 'friend', 'friends',
    'front', 'frontend', 'fs', 'ft', 'ftp', 'full', 'fun', 'function',
    'functional', 'fund', 'funding', 'funds', 'gadget', 'gallery', 'game',
    'gaming', 'gap', 'garage', 'garden', 'gas', 'gate', 'gateway', 'gather',
    'gauge', 'gay', 'gaze', 'gear', 'gender', 'gene', 'general', 'generate',
    'generator', 'generous', 'genesis', 'genius', 'geo', 'geography', 'get',
    'gift', 'git', 'github', 'give', 'gl', 'glam', 'glass', 'glb', 'global',
    'globe', 'go', 'goal', 'god', 'gold', 'golden', 'golf', 'good', 'goods',
    'google', 'gospel', 'gov', 'government', 'gp', 'gpl', 'grace', 'grade',
    'graduate', 'grain', 'grant', 'graph', 'graphic', 'graphql', 'grass',
    'great', 'green', 'grid', 'grocery', 'ground', 'group', 'groups', 'grow',
    'growth', 'gs', 'gsa', 'gsp', 'gt', 'guard', 'guess', 'guest', 'guide',
    'guild', 'gulf', 'guru', 'hack', 'hacker', 'hacking', 'hadoop', 'half',
    'hall', 'hand', 'handbook', 'hands', 'hang', 'happy', 'hard', 'hardware',
    'harmony', 'harvest', 'has', 'hat', 'hate', 'haven', 'head', 'header',
    'health', 'healthy', 'hear', 'heart', 'heat', 'heaven', 'heavy', 'hebrew',
    'height', 'hello', 'help', 'helpdesk', 'helpful', 'her', 'here', 'hero',
    'hey', 'hh', 'hi', 'hidden', 'hide', 'high', 'highlight', 'highway',
    'hiking', 'hindu', 'hint', 'hire', 'history', 'hit', 'hobby', 'hockey',
    'hold', 'holder', 'holiday', 'home', 'homes', 'honest', 'honey', 'honor',
    'hook', 'hope', 'horizon', 'host', 'hosting', 'hot', 'hotel', 'hour',
    'hours', 'house', 'housing', 'how', 'hub', 'hugo', 'human', 'humanity',
    'hundred', 'hunt', 'hunter', 'hurry', 'husband', 'hype', 'i18n', 'iam',
    'ice', 'icon', 'icons', 'id', 'idea', 'ideal', 'identification', 'identity',
    'ie', 'if', 'ig', 'ignite', 'image', 'images', 'imap', 'img', 'impact',
    'import', 'importer', 'impress', 'imprint', 'in', 'inbox', 'inc', 'include',
    'income', 'increase', 'index', 'india', 'indie', 'individual', 'industry',
    'infinite', 'influence', 'info', 'ing', 'ingress', 'init', 'initiative',
    'inject', 'inner', 'innovation', 'innovative', 'inquiry', 'ins', 'insight',
    'inspect', 'install', 'instance', 'instant', 'institute', 'insurance',
    'integrate', 'integrity', 'intel', 'intelligence', 'inter', 'interact',
    'interactive', 'interest', 'interface', 'internal', 'international',
    'internet', 'intervention', 'interview', 'intra', 'intro', 'invest',
    'investigate', 'investment', 'investor', 'invite', 'invoice', 'io',
    'ios', 'ipad', 'iphone', 'ipv4', 'ipv6', 'ir', 'iron', 'is', 'isa',
    'island', 'iso', 'issue', 'issues', 'it', 'item', 'items', 'its', 'ivr',
    'jabber', 'jack', 'japan', 'java', 'javascript', 'jazz', 'jboss', 'jdbc',
    'jenkins', 'jet', 'jewel', 'jira', 'job', 'jobs', 'joe', 'join', 'joint',
    'joke', 'jordan', 'journal', 'journey', 'joy', 'jquery', 'js', 'json',
    'jsp', 'jstl', 'judge', 'jul', 'july', 'jump', 'jun', 'junior', 'junk',
    'jupiter', 'jurisdiction', 'jury', 'just', 'justice', 'justify', 'kafka',
    'kansas', 'kappa', 'kayak', 'keep', 'keeper', 'kentucky', 'kernel', 'key',
    'keyboard', 'keys', 'kick', 'kid', 'kids', 'kill', 'kind', 'king', 'kiss',
    'kit', 'kitchen', 'kite', 'kitten', 'knife', 'knight', 'knit', 'knock',
    'knot', 'know', 'knowledge', 'known', 'knox', 'koala', 'kobe', 'korea',
    'kosher', 'kpi', 'kpop', 'kris', 'kronos', 'kube', 'kubernetes', 'kudos',
    'lab', 'label', 'labor', 'laboratory', 'labour', 'labs', 'ladder', 'lady',
    'lake', 'lamb', 'lambda', 'lamp', 'land', 'landing', 'landscape', 'language',
    'laptop', 'large', 'larry', 'laser', 'last', 'late', 'latest', 'latin',
    'latitude', 'laugh', 'launch', 'law', 'laws', 'lawyer', 'lay', 'layer',
    'layout', 'lazy', 'lead', 'leader', 'leadership', 'leading', 'learn',
    'learning', 'lease', 'least', 'leave', 'lecture', 'left', 'legacy',
    'legal', 'legend', 'lego', 'leisure', 'lemon', 'length', 'less', 'lesson',
    'let', 'letter', 'level', 'leverage', 'lex', 'liability', 'liberal',
    'liberty', 'library', 'license', 'life', 'lifestyle', 'lifetime', 'lift',
    'light', 'lighting', 'like', 'limit', 'limitation', 'limited', 'line',
    'linear', 'lines', 'link', 'linked', 'linkedin', 'links', 'linux', 'lion',
    'list', 'listen', 'listing', 'lists', 'literacy', 'literary', 'literature',
    'little', 'live', 'load', 'loader', 'loan', 'local', 'locale', 'localize',
    'location', 'lock', 'locker', 'locks', 'lodge', 'log', 'logic', 'login',
    'logo', 'logout', 'logs', 'long', 'look', 'lookup', 'loop', 'lord',
    'lose', 'loss', 'lost', 'lot', 'lots', 'lotto', 'louisiana', 'love',
    'low', 'lower', 'loyal', 'loyalty', 'ltd', 'lua', 'lucky', 'lunar',
    'lunch', 'lung', 'luxe', 'luxury', 'lyft', 'lynx', 'lyric', 'mac',
    'machine', 'machinery', 'macro', 'mad', 'madison', 'magazine', 'magic',
    'magnet', 'magnificent', 'maid', 'mail', 'mailbox', 'mailer', 'mailing',
    'main', 'mainland', 'mainstay', 'maintain', 'maintenance', 'major',
    'majority', 'make', 'maker', 'makes', 'makeup', 'male', 'mall', 'mama',
    'man', 'manage', 'management', 'manager', 'manga', 'manner', 'manual',
    'manufacturing', 'map', 'maple', 'mapping', 'maps', 'marathon', 'marble',
    'march', 'margo', 'marine', 'maritime', 'mark', 'market', 'marketing',
    'markets', 'marks', 'marriage', 'mars', 'marshall', 'mart', 'martin',
    'martini', 'mary', 'mask', 'mason', 'mass', 'massachusetts', 'massive',
    'master', 'masters', 'match', 'mate', 'material', 'math', 'matrix',
    'matter', 'mature', 'max', 'maximum', 'maybe', 'maze', 'mba', 'md',
    'me', 'meal', 'mean', 'meaning', 'measure', 'meat', 'mechanic', 'media',
    'median', 'medical', 'medium', 'meet', 'meeting', 'mega', 'member',
    'members', 'membership', 'memo', 'memorial', 'memory', 'men', 'mental',
    'mention', 'mentor', 'menu', 'merch', 'merchant', 'mercury', 'merge',
    'merit', 'merry', 'mesa', 'message', 'messages', 'meta', 'metal', 'meter',
    'method', 'metro', 'metropolitan', 'mexico', 'mgmt', 'mhz', 'mi', 'miami',
    'micro', 'microservice', 'microsoft', 'mid', 'middle', 'midwest', 'might',
    'migration', 'mike', 'milan', 'mild', 'mile', 'milestone', 'military',
    'mill', 'millennium', 'million', 'milo', 'mind', 'mine', 'miner', 'mineral',
    'mini', 'minimal', 'minimum', 'mining', 'minister', 'ministry', 'minor',
    'minority', 'mint', 'minute', 'mirror', 'miss', 'missile', 'mission',
    'missouri', 'mist', 'mistake', 'mix', 'mixed', 'mixture', 'mkt', 'mm',
    'mms', 'mo', 'mobile', 'mobility', 'mod', 'mode', 'model', 'models',
    'modem', 'moderate', 'modern', 'modest', 'modification', 'modify', 'module',
    'moisture', 'mom', 'moment', 'moments', 'monarch', 'monday', 'money',
    'monitor', 'monitoring', 'monkey', 'mono', 'monopoly', 'monster', 'month',
    'monthly', 'montreal', 'mood', 'moon', 'moral', 'more', 'morning', 'morph',
    'moscow', 'most', 'motel', 'mother', 'motion', 'motivate', 'motor', 'mount',
    'mountain', 'mouse', 'mouth', 'move', 'movement', 'movie', 'movies', 'moving',
    'mozilla', 'mr', 'mrs', 'ms', 'msg', 'msn', 'mt', 'mtv', 'mu', 'much',
    'mud', 'multi', 'multimedia', 'multiple', 'mumbai', 'municipal', 'museum',
    'music', 'musical', 'musician', 'must', 'mutual', 'mv', 'mw', 'mx', 'my',
    'mysql', 'mystery', 'myth', 'nagios', 'name', 'naming', 'nano', 'nasa',
    'nasdaq', 'nation', 'national', 'native', 'natural', 'nature', 'nav',
    'navigation', 'navy', 'nb', 'nc', 'nd', 'ne', 'near', 'neat', 'necessary',
    'need', 'negative', 'neglect', 'neighbor', 'neo', 'nepal', 'nerd', 'net',
    'netflix', 'netlify', 'network', 'networking', 'neural', 'neutral', 'never',
    'new', 'newark', 'newbie', 'newjersey', 'neworleans', 'news', 'newsletter',
    'newyork', 'next', 'nfl', 'ng', 'nginx', 'ni', 'nice', 'nick', 'night',
    'nike', 'nine', 'nirvana', 'nitro', 'nl', 'nm', 'no', 'nobel', 'noble',
    'node', 'nodejs', 'noise', 'nomad', 'non', 'none', 'north', 'northwest',
    'norway', 'nos', 'not', 'note', 'notebook', 'noteworthy', 'nothing',
    'notice', 'notification', 'notify', 'notion', 'nov', 'nova', 'novel',
    'november', 'now', 'nowhere', 'np', 'nr', 'ns', 'nsa', 'nuclear', 'null',
    'number', 'numbers', 'nurse', 'nut', 'nutrition', 'nv', 'nw', 'ny',
    'nyc', 'nz', 'oasis', 'oat', 'ob', 'obey', 'object', 'objective', 'obligation',
    'observation', 'observe', 'observer', 'obtain', 'occasion', 'occupy',
    'ocean', 'oclock', 'oct', 'october', 'od', 'odd', 'oe', 'off', 'offense',
    'offer', 'offering', 'office', 'official', 'often', 'oh', 'ohio', 'oil',
    'ok', 'oklahoma', 'ol', 'old', 'olympia', 'olympic', 'om', 'omaha', 'omega',
    'on', 'once', 'one', 'ongoing', 'online', 'ontario', 'oo', 'open', 'opening',
    'opera', 'operate', 'operation', 'operator', 'opinion', 'opponent', 'opportunity',
    'opposite', 'option', 'options', 'or', 'oracle', 'orange', 'orbit', 'order',
    'orders', 'ordinary', 'oregon', 'org', 'organ', 'organic', 'organisation',
    'organize', 'oriented', 'origin', 'original', 'orlando', 'os', 'oscar',
    'ot', 'other', 'otherwise', 'ou', 'ought', 'our', 'ours', 'out', 'outcome',
    'outdoor', 'outlook', 'output', 'outreach', 'outside', 'oven', 'over',
    'overall', 'overcome', 'overflow', 'overlook', 'overview', 'ow', 'own',
    'owner', 'ownership', 'ox', 'oxford', 'oxy', 'oz', 'p2p', 'pa', 'pacific',
    'pack', 'package', 'packaging', 'packet', 'page', 'pages', 'paid', 'pain',
    'paint', 'pair', 'pal', 'pale', 'palm', 'pan', 'panel', 'panic', 'panther',
    'paper', 'par', 'parade', 'paradox', 'paragraph', 'parallel', 'parent',
    'paris', 'park', 'parking', 'parliament', 'part', 'participate', 'particular',
    'partners', 'party', 'pass', 'passage', 'passenger', 'passion', 'passive',
    'passport', 'password', 'past', 'paste', 'pat', 'patch', 'patent', 'path',
    'patient', 'patriot', 'pattern', 'pause', 'pay', 'payment', 'payments',
    'paypal', 'pays', 'payout', 'pc', 'pci', 'pd', 'pe', 'peace', 'peak',
    'peer', 'pelican', 'pen', 'penalty', 'pencil', 'pending', 'peninsula',
    'pennsylvania', 'people', 'pepper', 'per', 'percent', 'percentage', 'perfect',
    'perform', 'performance', 'performer', 'permanent', 'permission', 'permit',
    'person', 'personal', 'personality', 'personnel', 'perspective', 'peru',
    'pet', 'petition', 'pg', 'ph', 'pharmacy', 'phase', 'phd', 'phenomenon',
    'philadelphia', 'philip', 'phoenix', 'phone', 'photo', 'photography', 'php',
    'phpmyadmin', 'physical', 'physician', 'physics', 'pi', 'piano', 'pick',
    'picture', 'pie', 'pigeon', 'pilot', 'pin', 'pine', 'pink', 'pioneer',
    'pipe', 'pipeline', 'pirates', 'pixel', 'pizza', 'pj', 'pk', 'place',
    'placement', 'plains', 'plan', 'plane', 'planet', 'planning', 'plant',
    'plasma', 'plastic', 'plate', 'platform', 'play', 'player', 'playground',
    'plaza', 'plc', 'pleasant', 'please', 'pleasure', 'plenty', 'plot', 'pls',
    'plug', 'plum', 'plus', 'pneumonia', 'po', 'pocket', 'poem', 'poetry',
    'point', 'poland', 'polar', 'pole', 'police', 'policy', 'polish', 'polite',
    'political', 'politics', 'poll', 'pollution', 'polo', 'pony', 'pool', 'poor',
    'pop', 'pope', 'popular', 'population', 'porch', 'port', 'portal', 'porter',
    'portfolio', 'portion', 'portrait', 'pose', 'position', 'positive', 'possess',
    'possibility', 'possible', 'post', 'postal', 'poster', 'postgres', 'pot',
    'potato', 'potential', 'pound', 'poverty', 'powder', 'power', 'powerful',
    'pp', 'practice', 'prague', 'prairie', 'pray', 'pre', 'preach', 'precious',
    'predict', 'prefer', 'preference', 'pregnancy', 'premier', 'premium',
    'preparation', 'prepare', 'prescribe', 'presence', 'present', 'preserve',
    'presidency', 'president', 'press', 'pressure', 'prevent', 'price', 'prices',
    'pride', 'priest', 'primary', 'prime', 'prince', 'princess', 'principal',
    'print', 'printer', 'prism', 'prison', 'privacy', 'private', 'privilege',
    'prize', 'pro', 'proactive', 'problem', 'procedure', 'proceed', 'process',
    'produce', 'producer', 'product', 'production', 'products', 'professional',
    'professor', 'profile', 'profit', 'program', 'programming', 'progress',
    'project', 'projection', 'promise', 'promote', 'promotion', 'prompt', 'proof',
    'prop', 'proper', 'property', 'proposal', 'propose', 'prospect', 'protect',
    'protection', 'protein', 'protest', 'protocol', 'prototype', 'proud', 'prove',
    'proven', 'provide', 'provider', 'province', 'provision', 'proxy', 'prs',
    'ps', 'psychology', 'pt', 'pub', 'public', 'publication', 'publicity',
    'publish', 'publisher', 'publishing', 'pudding', 'pull', 'pulse', 'pump',
    'punch', 'puppy', 'purchase', 'pure', 'purple', 'purpose', 'pursue', 'push',
    'put', 'puzzle', 'py', 'pyramid', 'python', 'qatar', 'qa', 'qos', 'qq',
    'qt', 'quad', 'quake', 'quality', 'quantity', 'quantum', 'quarter', 'queen',
    'query', 'question', 'queue', 'quick', 'quiet', 'quilt', 'quit', 'quiz',
    'quote', 'rabbit', 'race', 'racial', 'radar', 'radar', 'radio', 'radius',
    'rain', 'rainbow', 'raise', 'random', 'range', 'rank', 'rapid', 'rare',
    'ras', 'rate', 'rather', 'rating', 'ratio', 'raw', 'ray', 'reach', 'react',
    'read', 'reader', 'readiness', 'reading', 'ready', 'real', 'realestate',
    'realistic', 'reality', 'realize', 'really', 'realm', 'realtor', 'rear',
    'reason', 'reasonable', 'rebel', 'recall', 'receive', 'recent', 'reception',
    'recipe', 'recipient', 'recognize', 'recommend', 'reconcile', 'record',
    'recorder', 'recover', 'recovery', 'recreation', 'recruit', 'rectangle',
    'recycle', 'red', 'reduce', 'redundant', 'refer', 'reference', 'referral',
    'reflect', 'reform', 'refresh', 'refuge', 'refugee', 'refund', 'refuse',
    'regard', 'regime', 'region', 'regional', 'register', 'registration',
    'registry', 'regular', 'regulate', 'regulation', 'rehab', 'rehearsal',
    'reign', 'reinforce', 'reject', 'relate', 'relation', 'relative', 'relax',
    'release', 'relevant', 'reliability', 'reliable', 'relief', 'religion',
    'religious', 'relocate', 'rely', 'remain', 'remark', 'remember', 'remind',
    'remote', 'remove', 'render', 'renew', 'renewal', 'rent', 'rental', 'repair',
    'repeat', 'replace', 'report', 'reporter', 'reports', 'represent', 'repress',
    'reproduce', 'republic', 'reputation', 'request', 'require', 'rescue',
    'research', 'reseller', 'reserve', 'reset', 'resident', 'resign', 'resist',
    'resolve', 'resort', 'resource', 'resources', 'respect', 'respond', 'response',
    'responsibility', 'responsible', 'rest', 'restaurant', 'restore', 'restrict',
    'result', 'resume', 'retail', 'retire', 'return', 'reunion', 'reveal',
    'revenge', 'revenue', 'reverse', 'review', 'reviewer', 'revolution', 'reward',
    'rfc', 'rhode', 'rhythm', 'ribbon', 'rice', 'rich', 'richard', 'ride', 'rider',
    'ridge', 'rifle', 'right', 'ring', 'rio', 'risk', 'river', 'road', 'roam',
    'roar', 'roast', 'rob', 'robot', 'rock', 'rocket', 'rocky', 'rod', 'role',
    'roll', 'romance', 'romania', 'rome', 'roof', 'room', 'root', 'rose', 'rotation',
    'rough', 'round', 'route', 'routine', 'rover', 'row', 'royal', 'rpm', 'rsa',
    'ruby', 'rugby', 'rule', 'rules', 'ruler', 'run', 'runner', 'running', 'rural',
    'rush', 'russia', 'ruth', 'rw', 'ryan', 's3', 'sa', 'sad', 'safe', 'safety',
    'sail', 'sailor', 'salad', 'salary', 'sale', 'sales', 'salmon', 'salt', 'salvage',
    'same', 'sample', 'sand', 'sandbox', 'sanitation', 'santa', 'sao', 'sap',
    'sat', 'satellite', 'satisfaction', 'satisfy', 'saturday', 'saturn', 'save',
    'saving', 'savings', 'saw', 'say', 'scale', 'scan', 'scanner', 'scare', 'scatter',
    'scenario', 'scene', 'scenario', 'schedule', 'scheduler', 'schema', 'scheme',
    'scholar', 'scholarship', 'school', 'science', 'scientific', 'scientist', 'scope',
    'score', 'scoring', 'scotland', 'scout', 'scratch', 'screen', 'screens', 'script',
    'scroll', 'scsi', 'sculpture', 'sea', 'search', 'seas', 'season', 'seat',
    'second', 'secondary', 'secret', 'secretariat', 'secretary', 'section', 'sector',
    'secure', 'security', 'see', 'seed', 'seek', 'seeker', 'seem', 'segment', 'seize',
    'select', 'selection', 'self', 'sell', 'semester', 'semi', 'seminar', 'senate',
    'senator', 'send', 'senior', 'sense', 'sensitive', 'sensor', 'sensory', 'sent',
    'sentence', 'separate', 'sequence', 'series', 'serious', 'serve', 'server',
    'service', 'services', 'serving', 'session', 'set', 'setting', 'settle', 'seven',
    'several', 'sex', 'sexual', 'sh', 'shade', 'shadow', 'shake', 'shall', 'shame',
    'shape', 'share', 'shared', 'shares', 'shareware', 'shark', 'sharp', 'she',
    'sheep', 'sheet', 'shelf', 'shell', 'shelter', 'shift', 'shine', 'ship', 'shirt',
    'shock', 'shoe', 'shoot', 'shop', 'shopper', 'shopping', 'shore', 'short',
    'shot', 'shoulder', 'show', 'shower', 'shuffle', 'shut', 'si', 'sibling',
    'sick', 'side', 'sight', 'sign', 'signal', 'signature', 'significance', 'silent',
    'silk', 'silver', 'similar', 'simple', 'simulate', 'sin', 'since', 'sing',
    'singer', 'single', 'singles', 'sink', 'sir', 'sister', 'sit', 'site', 'situation',
    'six', 'size', 'sk', 'skate', 'skeleton', 'ski', 'skill', 'skin', 'skip',
    'skirt', 'sky', 'sl', 'slack', 'slam', 'slave', 'sleep', 'slide', 'slight',
    'slim', 'slip', 'slope', 'slow', 'small', 'smart', 'smash', 'smell', 'smile',
    'smith', 'smoke', 'smooth', 'sn', 'snake', 'snap', 'snow', 'so', 'soap', 'soccer',
    'social', 'society', 'socket', 'soft', 'software', 'soil', 'solar', 'soldier',
    'solid', 'solution', 'solve', 'som', 'some', 'son', 'song', 'sonic', 'soon',
    'sophisticated', 'sorry', 'sort', 'soul', 'sound', 'soup', 'source', 'south',
    'southwest', 'soviet', 'sox', 'space', 'spa', 'spain', 'span', 'spare', 'spark',
    'spatial', 'speak', 'speaker', 'special', 'species', 'specific', 'spectrum',
    'speech', 'speed', 'spell', 'spend', 'sphere', 'spin', 'spirit', 'spiritual',
    'spite', 'split', 'spoke', 'sponsor', 'sport', 'sports', 'spot', 'spread',
    'spring', 'square', 'squeeze', 'squirrel', 'sr', 'ss', 'ssl', 'st', 'stable',
    'stack', 'stadium', 'staff', 'stage', 'stain', 'stake', 'stamp', 'stand',
    'standard', 'standing', 'star', 'stare', 'start', 'state', 'statement', 'station',
    'statistics', 'status', 'stay', 'steady', 'steal', 'steam', 'steel', 'step',
    'stereo', 'stick', 'still', 'stock', 'stomach', 'stone', 'stop', 'storage',
    'store', 'storm', 'story', 'straight', 'strain', 'strange', 'strategic', 'strategy',
    'stream', 'street', 'strength', 'stress', 'stretch', 'strict', 'strike', 'string',
    'strip', 'stroke', 'strong', 'structure', 'struggle', 'stuck', 'student', 'studio',
    'study', 'stuff', 'style', 'sub', 'subject', 'sublime', 'submarine', 'submit',
    'subscribe', 'subscriber', 'subscription', 'subsequent', 'substance', 'subtle',
    'suburb', 'succeed', 'success', 'such', 'suck', 'sudden', 'suffer', 'sugar',
    'suggest', 'suite', 'sum', 'summary', 'summer', 'summit', 'sun', 'sunday',
    'sunrise', 'sunset', 'super', 'superior', 'supply', 'support', 'suppose', 'supreme',
    'sure', 'surface', 'surge', 'surplus', 'surprise', 'surround', 'survey', 'survival',
    'survive', 'suspect', 'suspend', 'sustainable', 'suv', 'sw', 'swallow', 'swan',
    'swap', 'sweden', 'sweet', 'swift', 'swim', 'swing', 'switch', 'swiss', 'sword',
    'sydney', 'sympathy', 'symphony', 'symptom', 'syn', 'sync', 'syndicate', 'syndrome',
    'synergy', 'syrup', 'system', 't-shirt', 'ta', 'tab', 'table', 'tablet', 'tackle',
    'tactical', 'tag', 'tail', 'take', 'tale', 'talent', 'talk', 'tall', 'tank',
    'tanzania', 'tape', 'target', 'task', 'taste', 'tax', 'taxi', 'taylor', 'tcp',
    'teach', 'teacher', 'teaching', 'team', 'tech', 'technical', 'technique', 'technology',
    'teen', 'teenage', 'telecom', 'telephone', 'telescope', 'television', 'tell',
    'temp', 'template', 'temple', 'temporary', 'ten', 'tenant', 'tend', 'tender',
    'tennis', 'tense', 'tension', 'term', 'terminal', 'terms', 'terrace', 'terrain',
    'terrible', 'territory', 'terror', 'test', 'testament', 'testimony', 'testing',
    'texas', 'text', 'textile', 'texture', 'thai', 'than', 'thank', 'that', 'the',
    'theater', 'theatre', 'theme', 'themselves', 'then', 'theory', 'therapy', 'there',
    'thick', 'thin', 'thing', 'think', 'third', 'thirty', 'this', 'thomas', 'those',
    'though', 'thought', 'thousand', 'thread', 'three', 'thriller', 'thrive', 'throat',
    'through', 'throw', 'thumb', 'thunder', 'thus', 'ticket', 'tie', 'tight', 'time',
    'timeline', 'timer', 'times', 'tiny', 'tip', 'tire', 'titan', 'title', 'toast',
    'today', 'todd', 'toe', 'together', 'token', 'tolerance', 'toll', 'tom', 'tomato',
    'tomorrow', 'tone', 'tongue', 'tonight', 'too', 'tool', 'tools', 'top', 'topic',
    'toronto', 'torture', 'total', 'touch', 'tough', 'tour', 'tourism', 'tournament',
    'toward', 'tower', 'town', 'toy', 'track', 'tracking', 'tracks', 'trade', 'trader',
    'trading', 'tradition', 'traffic', 'trail', 'train', 'training', 'trait', 'tram',
    'transaction', 'transcript', 'transfer', 'transform', 'transformation', 'transit',
    'translate', 'translation', 'transmission', 'transparent', 'transport', 'trash',
    'travel', 'traveler', 'treat', 'treatment', 'treaty', 'tree', 'trend', 'trial',
    'tribe', 'tribune', 'tribunal', 'trick', 'trip', 'triple', 'triumph', 'troop',
    'tropical', 'trouble', 'truck', 'true', 'trust', 'truth', 'try', 'ts', 'tube',
    'tuesday', 'tune', 'tunnel', 'turn', 'tv', 'twelve', 'twenty', 'twin', 'twist',
    'two', 'ty', 'type', 'typical', 'uc', 'udp', 'uganda', 'uh', 'uk', 'ultimate',
    'ultra', 'um', 'umbrella', 'un', 'unable', 'unbelievable', 'unc', 'uncertain',
    'uncle', 'uncommon', 'unconscious', 'under', 'understand', 'underwater', 'unfair',
    'unfold', 'unhappy', 'unified', 'union', 'unique', 'unit', 'unite', 'united',
    'unity', 'universal', 'universe', 'university', 'unknown', 'unless', 'unlikely',
    'unlock', 'unusual', 'up', 'update', 'upgrade', 'uphold', 'upon', 'upper',
    'upright', 'upset', 'urban', 'urge', 'urgent', 'url', 'us', 'usa', 'usage',
    'usd', 'use', 'used', 'useful', 'user', 'users', 'usual', 'utility', 'utilize',
    'utah', 'uup', 'ux', 'v2', 'v3', 'vacation', 'vacuum', 'vague', 'valid', 'valley',
    'valuable', 'value', 'values', 'valve', 'van', 'vancouver', 'vandal', 'vanish',
    'vapor', 'variable', 'variation', 'variety', 'various', 'vary', 'vast', 'vault',
    'vector', 'vegan', 'vegetable', 'vehicle', 'vein', 'venezuela', 'venture', 'venue',
    'verdict', 'verge', 'verify', 'version', 'versus', 'vertical', 'very', 'vessel',
    'veteran', 'veterinary', 'via', 'viable', 'vibrant', 'vice', 'victim', 'victory',
    'video', 'videos', 'view', 'viewer', 'viewpoint', 'village', 'vintage', 'violate',
    'violation', 'violence', 'virtual', 'virtue', 'virus', 'visible', 'vision', 'visit',
    'visual', 'vital', 'vocal', 'voice', 'void', 'vol', 'volatile', 'volume', 'volunteer',
    'vote', 'voter', 'voting', 'voyage', 'vpn', 'vs', 'vulnerability', 'w3', 'wade',
    'wag', 'wage', 'wagon', 'wait', 'waiter', 'wake', 'walk', 'wall', 'walmart',
    'walnut', 'walter', 'wan', 'wander', 'want', 'war', 'ward', 'ware', 'warehouse',
    'warm', 'warn', 'warning', 'warrant', 'warrior', 'was', 'wash', 'washington',
    'waste', 'watch', 'water', 'wave', 'wax', 'way', 'we', 'weak', 'wealth', 'weapon',
    'wear', 'weather', 'web', 'webapp', 'webcam', 'webdev', 'webhook', 'webmail',
    'webmaster', 'websocket', 'website', 'wed', 'wedding', 'wednesday', 'week',
    'weekend', 'weekly', 'weigh', 'weight', 'welcome', 'welfare', 'well', 'west',
    'western', 'wet', 'wheat', 'wheel', 'when', 'where', 'which', 'while', 'whisper',
    'white', 'who', 'whole', 'whom', 'why', 'wide', 'wifi', 'wiki', 'wild', 'wildlife',
    'will', 'willing', 'win', 'wind', 'window', 'wine', 'wing', 'winner', 'winter',
    'wire', 'wireless', 'wisdom', 'wise', 'wish', 'with', 'within', 'without', 'witness',
    'wizard', 'wolf', 'woman', 'wonder', 'wood', 'word', 'work', 'worker', 'workflow',
    'workforce', 'working', 'workplace', 'works', 'workshop', 'world', 'worried',
    'worry', 'worse', 'worth', 'would', 'wound', 'wow', 'wp', 'wrap', 'write', 'writer',
    'writing', 'written', 'wrong', 'wrote', 'ws', 'wt', 'wy', 'xbox', 'xerox', 'xls',
    'xmas', 'xml', 'xray', 'xyz', 'y2k', 'yahoo', 'yard', 'year', 'yellow', 'yes',
    'yesterday', 'yield', 'ymca', 'yoga', 'york', 'young', 'your', 'youth', 'yt',
    'yuan', 'z', 'zebra', 'zen', 'zero', 'zig', 'zimbabwe', 'zinc', 'zip', 'zone',
    'zoo', 'zoom', 'zulu', 'zurich'
]

def get_subdomains():
    return SUBDOMAINS

def get_subdomain_count():
    return len(SUBDOMAINS)
